### ISSUE TITLE
'stack template is shared with team' notification appears for the already shared template when it's updated.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10142]

**Comment by hakankaradis** [comment]
@diclee 
Could you please add a screencast for this bug?

**Comment by diclee** [comment]
![gif](http://g.recordit.co/TD9aSHuDp8.gif)
http://recordit.co/TD9aSHuDp8

1) Edit default stack
2) Save
3) You'll get 'stack template is shared with team' notification
but it was already shared with team before.

**Comment by diclee** [comment]
Verify passed on sandbox.
