### ISSUE TITLE
Collaboration invitation is not displayed for the participant and collaboration session ends unexpectedly after the participant tries the link (on latest)

### ISSUE THREAD

**Issue by diclee** [koding/koding#10144]
## Current Behavior
![gif](http://g.recordit.co/tPWE6JoeCH.gif)
http://recordit.co/tPWE6JoeCH

**Comment by cihangir** [comment]
Is this only reproducible on latest? if yes i can say we are safe for `collaboration session ends unexpectedly `, since we have changed the architecture to store session for collaboration

I need to check what might be wrong with collab invitation not shown

**Comment by diclee** [comment]
@cihangir yes, it's working on sandbox but broken on latest.

**Comment by cihangir** [comment]
i couldn't reproduce it, we should be good. once we deploy to prod will make sure it works by checking again.

**Comment by diclee** [comment]
@cihangir I've tried on both existing and new teams on latest and it's still not working. Therefore I'm not closing the issue until it's verified on production.

**Comment by cihangir** [comment]
Hey @diclee i have only tried in local & sandbox, where i couldnt reproduce.

**Comment by diclee** [comment]
@cihangir it's not reproducible on sandbox but only latest.

**Comment by diclee** [comment]
It's not reproducible on latest anymore. Closing the issue.
