### ISSUE TITLE
Copy change on 'do not warn' modal for shared stack template

### ISSUE THREAD

**Issue by diclee** [koding/koding#10146]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/21535196/92a7f60c-cd26-11e6-816f-12413e68c803.png)

Correct copy _may be:_ 'After clicking yes, you will not receive updates for this stack anymore.'

**Comment by diclee** [comment]
The modal is still the same, changes didn't take effect.

**Comment by cihangir** [comment]
I cant find any word containing `recieve` in the code base https://github.com/koding/koding/search?utf8=%E2%9C%93&q=recieve 

Could it be your cache?

**Comment by ppknap** [comment]
@cihangir from my experience Github's word indexing is not perfect.

The sentence is here:
```sh
~/koding/koding$ grep -rn "will not recieve\b" .
./client/app/lib/providers/computecontroller.ui.coffee:386:          message : '<h2>By clicking Yes, You will not recieve anymore update for this stack.</h2>'
```

**Comment by cihangir** [comment]
@ppknap you may not have the latest upstream https://github.com/koding/koding/blob/master/client/app/lib/providers/computecontroller.ui.coffee#L386

btw i use ag https://github.com/ggreer/the_silver_searcher it is way faster for searching text, highly recommended :)

**Comment by diclee** [comment]
Verify passed on latest.
