### ISSUE TITLE
Shared stack template is removed from sidebar after making it private.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10156]
## Current Behavior
![gif](http://g.recordit.co/ifODortOM4.gif)
http://recordit.co/ifODortOM4

It happens when it's only a draft and doesn't have a stack initialized.
After opening the dashboard, it's added back to the sidebar.

**Comment by hakankaradis** [comment]
This is because of we don't show the drafts in the sidebar.
and when you open the dashboard it triggers the draft's visibility and the draft is added back to sidebar.
I'll investigate it now and try to come up with a solution. @diclee

**Comment by hakankaradis** [comment]
@diclee 
When you create a draft and share it, it was also disappeared from sidebar, the pull request solves that problem too.

**Comment by diclee** [comment]
Verify passed on latest.
