### ISSUE TITLE
Stuck in an infinite loop between 'IDE' and collaboration routes when there's no machine on sidebar

### ISSUE THREAD

**Issue by diclee** [koding/koding#10185]
## Current Behavior
![gif](http://g.recordit.co/pVk85y0LlP.gif)
http://recordit.co/pVk85y0LlP

**Comment by szkl** [comment]
Fixed by https://github.com/koding/koding/pull/10114

**Comment by diclee** [comment]
@szkl this issue is still reproducible and not fixed with the above PR.
Below is the case when the invitation doesn't appear:
![gif](http://g.recordit.co/D9JQpShMbW.gif)
http://recordit.co/D9JQpShMbW

when the invitation appears and the participant accepts:
![gif](http://g.recordit.co/bE4cOOe7Qh.gif)
http://recordit.co/bE4cOOe7Qh

**Comment by szkl** [comment]
I can't reproduce the issue in both cases. A new stack is created in the sidebar when I navigate to a collaboration URL after destroying existing stack. I cannot replicate your scenario here. Accepting invitation works fine for me. Are there any errors in the console? Could you share your steps?

**Comment by diclee** [comment]
This happens when a member has no stacks at all. If you just destroy default team stack, it'll reappear with the page reload. Try to reproduce for a team that has no team default so that a newly joined member won't have any stacks.

**Comment by diclee** [comment]
This issue is not reproducible anymore. Closing.
