### ISSUE TITLE
Old team stack remains as a draft on sidebar for all members until reloading the page.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10202]
## Current Behavior
![gif](http://g.recordit.co/ZBMphDSA8k.gif)
http://recordit.co/ZBMphDSA8k

**Comment by diclee** [comment]
@hakankaradis I couldn't reproduce it again, if you cannot reproduce it as well, we can close it right away.

**Comment by hakankaradis** [comment]
#10204 looks like related with this bug.
I will investigate it and solve it soon.

**Comment by diclee** [comment]
@hakankaradis this issue is still reproducible for the admin/owner of the team that creates another stack and makes it team default stack:
![gif](http://g.recordit.co/FVWUj7eUml.gif)
http://recordit.co/FVWUj7eUml

Or is this the new behavior? Are we going to keep all previous team stacks on sidebar?

**Comment by hakankaradis** [comment]
@diclee This is expected behavior, because in your example, `kabuta stack` which is old default stack template is still shared with team, we are keeping the shared stack templates in the sidebar not all stack templates.

**Comment by diclee** [comment]
@hakankaradis ok, then this is the expected behavior from now on (it wasn't like this before), and owners/admins will have all old team default stack templates on sidebar, right?

**Comment by hakankaradis** [comment]
@diclee yes, because its access level is group.(shared with team)

**Comment by diclee** [comment]
Verify passed on latest.
