### ISSUE TITLE
SEND INVITES does not look like a CTA

### ISSUE THREAD

**Issue by diclee** [koding/koding#10205]
## Current Behavior
People are having hard time locating it

![image](https://cloud.githubusercontent.com/assets/8261892/21627634/0a86c2b0-d1ce-11e6-8f40-a77c013e6fba.png)

**Comment by ftasdelen** [comment]
We can add a button instead of the link. We can make it faded if user doesn't enter any recipient. When they enter any, we can make the button 100% visible.
![image](https://cloud.githubusercontent.com/assets/306264/21657453/2f098d3a-d277-11e6-97f0-c7413bc8bcda.png)

cc @diclee

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
