### ISSUE TITLE
Resend Invitation doesn't work

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#10270]
Resending invitation from teammates section throws XHR 502 error

![](https://monosnap.com/file/ylUc3Zcx1dg5qZwNOe2qCMM9pyr5aJ.png)

/cc: @diclee @gokmen

**Comment by diclee** [comment]
@hakankaradis resending invitation by entering the same email address also throws the same error. But the functionality seems to be working as the resent invitations are received by the participants.

**Comment by cihangir** [comment]
is this still valid? it seems the corresponding PR is merged

**Comment by diclee** [comment]
It's still valid as above merged PR was just related with this issue and not a fix.

**Comment by hakankaradis** [comment]
@diclee @cihangir the resend invitation doesn't work pr is opened again, fyi

**Comment by diclee** [comment]
Verify passed on sandbox.
