### ISSUE TITLE
stacks: add a default stack template per provider to the db

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#10294]
Currently default stack templates are hardcoded in the client/lib and are going to be also added to kloud/kd in order to support `kd template create`.

Also in order to e.g. change default Ubuntu distro for Marathon Stack we'd need to make a new deployment for that.

How about we add them to mongo instead, as JStackTemplate documents (and eventually some remote.api endpoint for fetching them)?

**Comment by cihangir** [comment]
even they could be just json documents served statically via nginx - just another idea

**Comment by gokmen** [comment]
I can expose an endpoint for default templates over remote.api (which can require it existing files from clientside) we don't need to store them in db. both kloud/kd and social backend can use it from there.

**Comment by rjeczalik** [comment]
@gokmen This also solves the problem. But there's another semi-related issue involved here.

Currently provider metadata is configured both in socialworker and in kloud. Kloud is able to output provider metadata as json during build time (api endpoint in runtime is also possible) via `kloud -genschema kloud.json` command.

The example output looks like the following:

https://gist.github.com/rjeczalik/f99d1279d2a3f24adb9e01b55eeb16e8

Kd is using this information to provide interactive mode for creating credentials - there's no actual logic per provider in kd - kd asks kloud what providers it has configured and gets the metadata, basing on which it builds dynamically the interactive mode (the part in the middle):

```
$ kd credential create
Provider type []: aws
Title [rjeczalik Sat Jan 14 10:13:18 2017]:
```
```
Access Key ID [***]: 
Secret Access Key [***]: 
Region [us-east-1]:
```
```
Team name [foobar]: 
Creating credential... 
error executing "create" command: error creating credential: aws: access key is invalid (e4d88013692cc67f)
``` 

Moreover currently we keep provider metadata both in socialworker and in kloud.

To the point - what about making socialworker use kloud-generated metadata. This way the default templates could be also part of provider metadata and always in-sync with kloud providers.

**Comment by gokmen** [comment]
ref: https://github.com/koding/koding/pull/10343
