### ISSUE TITLE
Providing a secure api endpoint for webhooks

### ISSUE THREAD

**Issue by gokmen** [koding/koding#10359]
We want to provide a way to use `remote.api` endpoints for hook like operations eg. `build a given stack template when a new branch pushed to github`. 

To be able to do that we simply can add related `remote.api` endpoint to the repository web hook settings in GitHub. But, most of the web hook integrations (including GitHub) does not support customising the header of the request or adding a custom data into the payload (like a token). 

They mostly provide defining a secret keyword in web hook settings which provides a hash (`X-***-Signature`) in header on each request; which is generated from encrypted payload with provided `secret key` (RFC 2104 https://www.ietf.org/rfc/rfc2104.txt). Which requires both requester and sender to know `secret key` and it’s not possible to query by with multiple options (like in `apiTokens` or `sessionId` -aka `clientId`- ’s that we have) For this reason we cannot use `clientId` as `secret key` in this scenario.

### RFC-2104 Compliant Secret Key Support

We can define a secret field in `JGroupData` for this secret keyword usage which will be per team and can be used as a secret hashing key for RFC-2104. But with this implementation we loose the possibility to have multiple api user support per team. Also if we use an `apiToken` for this field it will be `JGroup` only which won’t allow us to use it directly for `remote.api` (we need to have a clientId which includes user + group information for api access) even though current implementation of `JApiToken` includes `originId` as creator’s JAccount._id we cannot use this one since user can be kicked from team.

### Generating Hook Mechanism

With this one we can define a new hook mechanism on Koding and for each hook we can define the action that needs to be taken. We can have a new collection for hook definitions like;

```
JHook
  action: “remote.api/JStackTemplate.build/XXXX”
  group: “your-team”
  identifier: “foobarbazunique” # auto-generated
  originId: ObjectId            # JAccount._id of owner
```

which will be called like `remote.api` but doesn’t require authorisation header;

`https://your-team.koding.com/**remote.hook**/foobarbazunique`

once it’s called by an endpoint we will call the action defined in `JHook` on behalf of the user who has `originId`

This implementation requires more planning, UI and UX around it.

### Supporting Token in API Routes

Simply adding support to `remote.api` endpoints to pass clientId in route; calling following API route with Header;

`https://your-team.koding.com/remote.api/version`

will become;

`https://your-team.koding.com/remote.api/YOURTOKEN/version`

This implementation is the easiest one to implement with one caveat which allows anyone who has this url to do anything with the owner’s account.

WDYT?

cc/ @rjeczalik @cihangir @szkl @usirin @sinan @hakankaradis

**Comment by usirin** [comment]
It looks good to me overall. One addition I can make we can use a more standardized url scheme:

```
https://your-team.koding.com/remote.api/version/<endpoint>?t=YOURTOKEN
```

That way it really becomes a parameter in the url, rather than a real part of url itself. Also having `version` at the most front works better as a namespace (also it's one of the best practices of web service api design).

**Comment by gokmen** [comment]
@usirin I was actually asking which one should we choose? (it's my bad to not asking for it :) ) I assume you are ok with "token in api routes" solution but with queryString instead. I thought that one too but instead of mixing a `POST` request with `GET` params wouldn't it be better to make it a part of the route?

**Comment by gokmen** [comment]
@usirin btw that `version` was a valid endpoint from our api list not a variable. I also agree that we need version definition but currently our models has no support for versioning; we need to implement that one first and then we can update api routes easily since they are auto generated.

**Comment by rjeczalik** [comment]
@gokmen The idea with apiToken in hooks' URLs sounds good to me.

**Comment by sinan** [comment]
a hook mechanism would be the best but due to lack of time and ease of implementation I'd say let's go with "Supporting Token in API Routes"

**Comment by szkl** [comment]
Adding token in the URI is fine by me.

> This implementation is the easiest one to implement with one caveat which allows anyone who has this url to do anything with the owner’s account.

Can we restrict what can be done with a token through permissions?

**Comment by gokmen** [comment]
@szkl yes, in the longterm we can do such thing and define permission per token which can be used for taking action with that permission but it'll require more implementation. Let's write down the details and implement that one in the future.

**Comment by cihangir** [comment]
i liked 
```
JHook
  action: “remote.api/JStackTemplate.build/XXXX”
  group: “your-team”
  identifier: “foobarbazunique” # auto-generated
  originId: ObjectId            # JAccount._id of owner
```
and
```
https://your-team.koding.com/**remote.hook**/foobarbazunique
```

this opens up many possibilities like, modifying parameters of a function on the fly without requiring changes on the hook side

**Comment by gokmen** [comment]
@cihangir we can plan that out and I've some amazing plans around that :)

**Comment by gokmen** [comment]
ref: https://github.com/koding/koding/pull/10320
