### ISSUE TITLE
Adapt debug package for both be & fe requirements

### ISSUE THREAD

**Issue by gokmen** [koding/koding#10407]
We need a generic debug solution which `debug` package can be a solution at this point https://github.com/visionmedia/debug using it widely in side projects.

**Comment by gokmen** [comment]
cc/ @koding/developers

**Comment by cihangir** [comment]
This package only gives DEBUG as level (as the name states :) ) instead could we have a full fledged logging package, which will be enforced application-wide?  

Also could we have a unified log messages like `2017-01-24T06:01:49.256Z INFO [SocialAPI:0    ][PID:10972][logging/context.go:47] message goes here` `<date> <log level> <worker name> <pid of the process><log line> <message itself>` ? ( pid is N/A for browser )

**Comment by gokmen** [comment]
@cihangir I'm ok for logger but this one is only for debugging purposes, I mean I don't want to log a variable's value but I do want to see it's content when I enabled debugging while development. We can for sure integrate a generic logger as a separate issue. Sometimes I do need to put some console.logs some places which has no important information in it but it's required while I'm developing and once I'm done I had to remove them, this package will remove that requirement and will provide filterable debug outputs for developers.

**Comment by cihangir** [comment]
good log package(s) cover(s) the same requirements. i would like to have a full fledged log package in our system rather than a very specialized and opinionated package

https://github.com/trentm/node-bunyan looks promising, with all the features "debug"  package has and many others like we have in github.com/koding/logging

**Comment by gokmen** [comment]
this is not the same thing, logging is completely different requirement rather than debug, we can introduce this one as well if we needed to but it's not simple as like debug for a simple requirement. debugging is not logging.

**Comment by cihangir** [comment]
> debugging is not logging.

i would rather see explanation to this statement as a blog post. Because so many devs including me do "debug" mostly with logging. Incidentally you are proposing an opinionated logging solution. See
this  https://github.com/visionmedia/debug/blob/master/src/debug.js#L113

**Comment by gokmen** [comment]
> debugging is not logging.

it doesn't mean you can't use logging for debugging purposes, it means debugging requirement doesn't need to cover logging requirements. I don't want people to deal with logging details, just a simple debug call for debugging logs is enough and we don't need to log everything for debugging but for sure we can log anything that we want to log.

anyways I'll implement `debug` in places that I need debugging as is since I learned that we are already using it; 

- https://github.com/koding/koding/blob/master/package.json#L45 
- https://github.com/koding/koding/blob/master/node_modules_koding/bongo/lib/bongo.coffee#L15
- https://github.com/koding/kd/blob/master/lib/core/view.coffee#L1
