### ISSUE TITLE
FUSE notifications for new mounts architecture.

### ISSUE THREAD

**Issue by ppknap** [koding/koding#10419]
### FUSE notify workflow.

A single mount is described by followed values:

**ID** (`machine/mount/ID` type) - is a unique UUIDv4 identifier of the mount.
**Path** (`machine/mount/Mount.Path` field) - the local directory where mount is created.
**RemotePath** (`machine/mount/Mount.RemotePath` field) - remote folder which is mounted.

Both `Path` and `RemotePath` are stored together inside `Mount` [structure](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/mount/mount.go#L34)

For the sake of further reading lets take following mount:

ID: `123e4567-e89b-12d3-a456-426655440000`
Path: `/home/test/local`
RemotePath: `/home/test/remote`

The `Sync` [type](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/mount/sync/sync.go#L79) ensures that all paths exists. Moreover it creates a *cache* directory under:

```
$HOME/.cache/koding
```

with the following [structure](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/mount/sync/sync.go#L47):

```
$HOME/.cache/koding
+-mount-123e4567-e89b-12d3-a456-426655440000
|-data
| +-... // mounted directory cache.
|-index.remote
+-index.local
```

`data` directory contains the "real" files ie. these fetched from remote directory.
`index.remote` is a known state of remote directory tree (`/home/test/remote`).
`index.local` is a known state of `data` directory tree (`.cache/koding/mount-<UUID>/data`).

Note that there is no information about mounted Path (`/home/test/local`). It's the goal of this issue to use FUSE in order to create a **VIEW** to `data` directory.

This means that FUSE notifier should:

[ ] - create a mount point using FUSE and `Path`.
[ ] - ensures that if mount is already created it can reattach to it (unmount old mount and mount again which obviously will not change the `data` cache)
[ ] - the file view created by FUSE (inodes) should be taken from `remote.index` and not `data` cache. This allows to create the complete FS view without fetching any files.
[ ] - behaves as a proxy for FS operations.
[ ] - implements `Drop` method which is basically umount.

FUSE notifier should **not**
 - ensure that any of the files or remote dirs/indexes are missing/removed - its `Sync` responsibility.
 - fetch any data from remote machine directory. (all needed info will be stored inside indexes).

### Implementation details.

The folowing files should be created under `klient/machine/mount` directory:

```
notify
+fuse
|  +-fuse implementation goes here
+ notify.go
```

`notify.go` should have following interface declaration:

```go
type Ensurer interface {
    // Ensure takes the index.Change object and returns a channel which will be closed
    // when the following change is applied to both indexes.
    Ensure(c *index.Change) (<-chan error)
}
```

[index.Change](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/index/index.go#L89) `Meta` field will need to be extended with two additional bitmasks that indicates the direction of change. Eg.

 - when file is created on local directory in fuse, it creates a `ChangeMetaAdd` change and indicates that synchronization should be from local `data` cache to remote direcotry.
 - when someone tries to read unfetched file that does not exist in index.local, fuse will need to create `ChangeMetaAdd` change with remote->local direction

All these things can be done by adding two additional fields to `index.Cache.Mask` bitmask.

This also implies creating additional function inside `index` package with signature like:

```go
func FileChange(local, remote *Index, file string) (*Change, error)
```

that will cover cases above.

---------

When FUSE notifier is initialized, it should create mount filesystem or reattach to unmounted one (or fail otherwise). The `mountcli` package might be useful when detecting existing mounts (but might be also not necessary)

--------

The FUSE object should contain following fields:

```go
wd string // working dir of cache (mount-<UUID>/data.
m mount.Mount
local, remote *index.Index
ensure notify.Ensurer
```

During initialization it should create managed inodes [map and handlers](https://github.com/koding/koding/blob/master/go/src/koding/fuseklient/kodingnetworkfs.go#L66). Where note should use **index.remote**.

When one of fuse.Filesystem interface method is called, FUSE notifier should.
- check difference between remote and local indexes (`index.FileChange` method)
- if there is none, serve file from `mount-<UUID>/data` cache folder.
- if there is change, send it to ensurer and wait for resulting channel to close. It may also implement it's own timeout.
- if resulting ensurer error is nil, it should serve file from `mount-<UUID>/data` cache folder.

It's not FUSE notifier responsibility to update indexes.

- file attributes may be read directly from the index.
- during writes, FUSE notifier should write file to `mount-<UUID>/data` cache and call `index.FileChange` on stored file, then it should send resulted change to ensurer - it doesn't need to wait for resulting channel.

NOTE: FUSE can call write operation multiple times per single write. **It's ensurer responsibility** to squash/throttle incoming events so FUSE doesn't need to implement such logic.

-------

##### Testing.

One can use [mounttest.MountDirs](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/mount/mounttest/mounttest.go#L19) to create temporary "mount" directories. 

Indexes can be created by running [index.NewIndexFiles](https://github.com/koding/koding/blob/master/go/src/koding/klient/machine/index/index.go#L124) function on returned directories. (wd+"/data" and m.RemotePath)

Fake ensurer can just copy files from `wd+"/data"` directory to m.RemoteDirectory.

:warning: This means that FUSE notifier can be tested without `Sync` package.

Cases:
- creating FUSE object creates FUSE mount.
- creating FUSE object on not unmounted mount. (it should recover itself)
- basic FS operations should send `index.Changes` to fake ensurer.
- FS kernel timeouts.
- Kernel caching issues; (see: [fuse.Mountcfg](https://github.com/koding/koding/blob/master/go/src/koding/fuseklient/kodingnetworkfs.go#L116) 

This design might be changed by the implementer, these are not strict requirements.

**Comment by rjeczalik** [comment]
> It's ensurer responsibility to squash/throttle incoming events so FUSE doesn't need to implement such logic.

Any advice on coalescing interval?

**Comment by ppknap** [comment]
FUSE is not meant to do any coalescing on its side. Its `Ensurer`(or whatever it will be called) responsibility.

**Comment by ppknap** [comment]
Done by #10591
