### ISSUE TITLE
'Enter a credit card' modal appears for old teams although there's a valid saved card.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10496]
## Current Behavior
![gif](http://g.recordit.co/hDypsNu4OM.gif)
http://recordit.co/hDypsNu4OM

**Comment by cihangir** [comment]
fixed with https://github.com/koding/koding/issues/10496

**Comment by cihangir** [comment]
ps: hotpatched prod servers in the morning.

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
