### ISSUE TITLE
Koding logo is not displayed properly on invitation emails.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10494]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/22614345/b36d40be-ea35-11e6-8772-1c7570d2e106.png)

Also the one on the bottom is broken.

**Comment by sinan** [comment]
@diclee can you please forward that email to me?

**Comment by sinan** [comment]
not necessary anymore, I must have fixed all the emails. It was because some images were still served from hubspot's cdn. I changed them all to our own. If you still see some, please let me know.

**Comment by diclee** [comment]
Verify passed.
