### ISSUE TITLE
CredentialStore.storeOnMongo function doesn't validate user permissions for related group

### ISSUE THREAD

**Issue by szkl** [koding/koding#10719]
CredentialStore.storeOnMongo function validates user's permission inherently by Social API helper functions.

**Comment by gokmen** [comment]
why do you need that? it's a private class and only used by/over `JCredential` and it does the validation https://github.com/koding/koding/blob/master/workers/social/lib/social/models/computeproviders/credential.coffee#L181-L197

**Comment by szkl** [comment]
CI build for https://github.com/koding/koding/pull/10558/commits/bdc825e937875659438108e134991736fc0eee89 (https://github.com/koding/koding/pull/10558) in wercker failed because test runner was not setting CI environment variable which enabled sneaker storage for credentials. Credential saving process looked up for user's role in related group. Circle CI build was not failing because CI variable was set properly and credentials were stored in mongo. This process doesn't look up whether user is a member of that group or have any roles. So either all checks and validations must be done before deciding which storage system to use or both functions should apply same set of validation process to be consistent.

**Comment by gokmen** [comment]
> This process doesn't look up whether user is a member of that group or have any roles. 
This is not possible, as I showed here; it's passing through `create credential` permission 
https://github.com/koding/koding/blob/master/workers/social/lib/social/models/computeproviders/credential.coffee#L181-L197

There must be something else, I'll try to run tests on locally with Sneaker support and let you know but I'm pretty sure that it's not the cause.

**Comment by gokmen** [comment]
All tests passed and explicitly I've tried permission tests as well for credentials which are fine too.
Also,
> This process doesn't look up whether user is a member of that group or have any roles.

Credentials are not `group` depended so there is no relation between a credential and a group, all credentials are belong to the owner but they can share with groups. But, to be able to create a credential you need to have `create credential` permission on the group that you have your session currently.
