### ISSUE TITLE
Use default paths during `kd machine mount`

### ISSUE THREAD

**Issue by ppknap** [koding/koding#10714]
As suggested by @sinan - typing:
`kd machine mount <machine_(id|alias|ip)>`
should default to:
`kd machine mount <machine_(id|alias|ip)>:<remote/home/dir> <machine_alias>`

**Comment by devrim** [comment]
when absent on cli, /remote/home/dir tries to find $KD_MOUNT_HOMEFOLDER_DEFAULT on the remote VM and mounts that, if not falls back to $HOME

**Comment by ppknap** [comment]
Done by #11037
