### ISSUE TITLE
kd/auth: add whoami command 

### ISSUE THREAD

**Issue by sinan** [koding/koding#10737]
There isn't a clear way of understanding if the user is logged in.

`kd auth whoami` or shorter `kd whoami` can be added.

**Comment by rjeczalik** [comment]
I forgot about this previously, but we have something like:

```
$ kd team show
You are currently logged in to the following team: team
```

```
$  kd team show --json
{
	"name": "team"
}
```

@sinan For the `kd whoami` is the following information enough?

```
$  kd whoami --json
{
	"username: "sinan",
	"name": "team",
	"koding": "https://koding.com"
}
```

**Comment by sinan** [comment]
yeah looks good, should the last key be `koding` or `baseurl`?

**Comment by rjeczalik** [comment]
@sinan Yes, it should be `baseurl` as it is in `kd auth --baseurl`.
