### ISSUE TITLE
kloud/provider: add Kubernetes support

### ISSUE THREAD

**Issue by acbodine** [koding/koding#10776]
This serves as a retainer for the design and implementation of a Kubernetes provider for Koding.

## Overview

[Kubernetes](https://kubernetes.io/) is a container orchestration technology that has gained critical traction in the world of development and production devops centered around container-based application workloads. You can even bring over your existing `Dockerfile`s and Kubernetes will happily accept your Docker images into its workload abstractions called `pods`.

<img
    alt="Kubernetes Architecture Overview"
    width="600"
    src="https://github.com/kubernetes/kubernetes/raw/v1.5.1/docs/design/architecture.png?raw=true"
/>

You tell Kubernetes (with `kubectl`) what you want the topology of your application to look like `desired state`, usually by means of a YAML specification (deployment, replica set, job), and Kubernetes makes the `actual state` match the `desired state` in a safe and reliable way.

Interested in [design docs](https://github.com/kubernetes/kubernetes/tree/v1.5.1/docs/design) for Kubernetes?

As a basic example of a deployment specification to Kubernetes for nginx:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
This will result in Kubernetes:
1. Pulling the `ngingx:1.7.9` image from [Docker Hub](https://hub.docker.com/) if it doesn't already have it
2. Creating and running 3 containers from that image all listening on their own port 80s
3. Creating a service endpoint in the Kubernetes proxy that all 3 of the nginx containers serve.

The service endpoint should persist through application updates (rolling), so it is ideal for configuration/environment variables for consumers. This would be analogous to the public endpoint that current Koding stacks serve once provisioned based on their specific application port(s).

## Expected Behavior

What do we want/expect from Kubernetes?

As a Koding user I want to be able to configure the following for my Kubernetes Pod Stack:
- Images
- Scale
- Storage
- Network
- Quotas

> NOTE: Modifications to deployments running on Kubernetes that are done outside of Koding's knowledge, shouldn't break Koding's implementation. Have some sort of discovery process, the Kubernetes API should be able to make this a simple task.

Once my Pod Stack has been provisioned on the existing Kubernetes cluster, that I specify at stack creation/initialization, I should be able to access my Pod Stack from a Kubernetes service endpoint.

I also want the ability to:
- Exec into any container that Koding is aware of in the Kubernetes cluster
- Scale in/out any Pod Stack

## Current Behavior

As a close reference point, we are doing a small comparison with the existing Marathon provider for Koding. Currently the Marathon provider focuses on single container applications, given this restriction the implementation injects Koding's agent `klient` into the container via a startup script before running the user's application inside the container.

This isn’t great in terms of scale, and wrapping the application with an entrypoint script to install klient at container runtime is slow and hacky. Thus, we haven’t ruled out modifying `klient`.

While single container applications work great for the basic use cases, it might not be the most realistic view of how users expect to consume hosted container orchestration services. Perhaps a more realistic view is at least an application that has more than one process (multiple container images) and each of those processes needs to be scaled out. The number of `klient` processes that would be in play with the current approach, grows very rapidly.

## Possible Solution

If we take a step back, and let's say we rely on Kubernetes to do it's job, trust it even. All the Koding provider needs to do at that point is call the right Kubernetes API operations with the correct data structures representing the `desired state`. Every API operation from Kubernetes results in a [record of intent](https://kubernetes.io/docs/concepts/abstractions/overview/) response. Meaning Kubernetes will make the `actual state` match the `desired state` as soon as possible.

A possible solution that we have discussed briefly is to have a dedicated `klient` container per deployment that the provider deploys to Kubernetes cluster. There are certain guarantees that Kubernetes provides that makes this an appealing solution per deployment: 
- Co-located processes
- Shared storage (volumes)
- Shared network
- Shared namespaces
- Everyone fails or succeeds together (no half-functioning deployment)

In short, we are guaranteed that:
- if our deployment is up, our corresponding `klient` container is also up
- if our deployment is down for any reason, our corresponding `klient` container is also down

This would remove the need to inject an entrypoint script into each container image, and we would gain back any built-in Kubernetes features that the current approach would mask such as: healthchecking.

Possibly we should look into syncing Koding credentials to the provided Kubernetes cluster to leverage the benefits of Kubernetes providing credentials to user containers.

Kubernetes community maintains a Golang [client](https://github.com/kubernetes/client-go) so we can programmatically invoke the Kubernetes API to set `desired state`.

Do we still want to use Terraform under the covers here?
> It might not make sense to. Terraform is about provisioning cloud resources, and in our proposed > solution we believe the Kubernetes provider shouldn't be involved with managing the Kubernetes
> cluster (GCE, Bluemix Container Service, On-Prem), the provider should only
> create/update/destroy deployments/pods via the Kubernetes API. Terraform also assumes it is
> authoritative over cloud resources. If someone were to use `kubectl` outside of Koding
> there would likely be a difference in state records.

**Comment by rjeczalik** [comment]
@acbodine Thanks for summing it up and elaborating on the details.

I agree, I don't see much benefit of injecting klient per container, in my opinion we should have a klient per pod, with new API which will reverse proxy webterm sessions and alike to the containers within the pod. The sam API could be use to access containers on regular machines (e.g. AWS).

Other question is about networking, what to use to access klient within the pod from Koding backend. Currently we use a custom tunnelling service.

> Do we still want to use Terraform under the covers here?

I'm unable to see any use of Terraform here.

**Comment by acbodine** [comment]
@rjeczalik Can you add some details to this proposal on what the new klient API would look like?

I would think our options  for connecting to klient from Koding's backend are either:
- utilize the kubernetes [client-go](https://github.com/kubernetes/client-go) and exec to the containers via the Kubernetes API (seems like they don't support that yet https://github.com/kubernetes/client-go/issues/45)
- expose koding port 56789 via a Kubernetes service endpoint similar to the application port. Meaning each stack would have at least two service endpoints in Kubernetes

Is there any option for the connection to be established from the agent back to Koding's backend, and then maintain that connection with something like WebSockets? If the agent was ever rescheduled it would establish a new connection with Koding when it started up.

**Comment by rjeczalik** [comment]
> Can you add some details to this proposal on what the new klient API would look like?

@acbodine The API I'm thinking about should have:

- extended "klient.info" response with some kind of Type to indicate this klient serves as a proxy
- added e.g. "proxy.list" method to list details about all containers within the pod
- extended "webterm.connect" method, so Koding is able to connect to a container via the klient proxy
- extended "exec" / "os.exec" so it's possible to run an command with "kd exec" on any container within the pod
- extended "fs.\*" methods, required for Koding UI to draw file tree and execute actions like "perm" change and so on (but given the read-only nature of containers, it's discussible whether UI should allow for it - cc @gokmen)
- ... - possibly there's more, the above list is what I remember off-hand
 
> Is there any option for the connection to be established from the agent back to Koding's backend (...)

Klient announces its address to Koding via Register method call somewhere inside go/src/koding/klient/app package. Then Koding uses this address to connect to the klient, when needed. Currently klient obtains its address from two sources - either by reading it's public IP or it uses its tunnel ID. It should read its k8s service proxy address and register with it to Kontrol - then it would be possible to access such klient from Koding backend.

**Comment by acbodine** [comment]
> Currently klient obtains its address from two sources - ..
I'm not sure that a container knows about the Kubernetes service endpoint it is serving, especially since the container most likely doesn't have `host` networking. (There would only be one klient per Kubernetes Node). It might be was easier to query for the service endpoint with the Kubernetes API from Koding backend?

> Klient announces its address to Koding upon start via Register method ..
Still keep this behavior as it also helps let Koding know about Stack build success or failure. Maybe we follow this up with a query to the Kubernetes API to create/get the service endpoint from Koding backend.

**Comment by rjeczalik** [comment]
> It might be was easier to query for the service endpoint with the Kubernetes API from Koding backend?

Yes, that'd would be the right way to do it. I just described how this works currently.

**Comment by acbodine** [comment]
Should we maintain the klient API changes in a separate issue?

**Comment by rjeczalik** [comment]
> Should we maintain the klient API changes in a separate issue?

Yes, please, good idea.

**Comment by gbts** [comment]
Hi, I think I'm going to start working on this. Is the bounty still available?

**Comment by acbodine** [comment]
`klient` is getting there, need to validate `fs.*` kite methods for `klient` container, and validate/extend webterm/terminal kite methods.

**Comment by kristiandrucker** [comment]
Hey, how is this integration going? When it may be done?

**Comment by tardyp** [comment]
@acbodine did you have time to work on this? any code to share?

I was planning to assign @protatremy from my team to work on it. We probably were not as ambitious as this plan though.
We were planning to start from the marathon backend, and see how we can make it work on k8s.
Then gradually improve on making it right.

**Comment by acbodine** [comment]
@tardyp I had some time a little while back, and have code to share. The related issue #10790 is where my progress has been so far. The associated code here: https://github.com/acbodine/koding/tree/klient-proxy implements the necessary changes for `klient` to act as a proxy to Kubernetes API for specific commands kite methods.

The plan was:
- I have a few modifications to make in the `klient-proxy` branch according to @rjeczalik comments; I implemented the wrong kite method for execing, but should be able to re-use the hard part which was connecting to K8s APIs.
- There are front-end (UI) modifications that need to happen that I was discussing with @gokmen 
- Once those things happen, this issue can be tackled by creating a Kubernetes kloud provider that invokes the new APIs and UI workflows that are a result of #10790 

It has been a little bit since I was working on this. I have more time to pick this back up again, as long as nothing has changed? @rjeczalik @gokmen.

**Comment by ChrisCates** [comment]
![image](https://user-images.githubusercontent.com/1561091/45315981-c0dc6a00-b503-11e8-95a4-d6fb87428269.png)


https://github.com/koding/koding/pull/11505

**Comment by LemonAndroid** [comment]
Is someone already trying to claim the bounty?

**Comment by ChrisCates** [comment]
@LemonAndroid, for the most part... The bounty is redundant and shouldn't be fulfilled.
Since Kuburnetes' `kompose` is compatible with `docker-compose.yml` files.

**Comment by ChrisCates** [comment]
@LemonAndroid, I agree... For book keeping purposes, I created #11505 to clarify any existing issues between Docker and Kuburnetes.

Furthermore. this bounty has been sitting on BountySource.com for several years...
The Koding Maintainers have been active for almost 2 months as well...

My suggestion if you're looking for bounties is to check out @gitcoin and gitcoin.co.
They are much more active.

**Comment by LemonAndroid** [comment]
@ChrisCates Have or haven't been active?

**Comment by ChrisCates** [comment]
@LemonAndroid, haven't been active... Sorry for the typo.

**Comment by devrim** [comment]
This issue is closed. BountySource folks, please do not start.
