### ISSUE TITLE
Credit Card icon is not displayed correctly.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10826]
## Current Behavior
![gif](http://g.recordit.co/HuNwYXdShQ.gif)
http://recordit.co/HuNwYXdShQ

- It's displayed on the page for updating the card (and on the billing page after trying to update the card).

- It's not displayed again after logging out and relogin.

**Comment by usirin** [comment]
@diclee I couldn't get this reproduced. 

But one thing i noticed in your gif is that after the dashboard is loaded, your ide gets loaded as well on the background, and once it's loaded the card brand disappears. 

But in my case (i tested on sandbox as well) the ide never loads on the background, therefore the card brand stays as is.

We can test together, using the account on the gif, to reproduce the issue again.
