### ISSUE TITLE
Terminal is getting broken in some cases.

### ISSUE THREAD

**Issue by diclee** [koding/koding#10968]
## Current Behavior
![gif](http://g.recordit.co/KeUr9it2B3.gif)
http://recordit.co/KeUr9it2B3

In above example it's getting highlighted after running 'ls /' command.

**Comment by gokmen** [comment]
@rjeczalik this might be related with latest `cloud-init` updates that we need to dig into it. cc/ @szkl

**Comment by rjeczalik** [comment]
@diclee Is it on sandbox or production? What's the kite ID and is username `veronicamars`?

**Comment by diclee** [comment]
Verify passed on latest.
