### ISSUE TITLE
Cursor goes to the end after each letter typed on 'stack name' field

### ISSUE THREAD

**Issue by diclee** [koding/koding#11022]
## Current Behavior
![gif](http://g.recordit.co/9KIJ2QGboM.gif)
http://recordit.co/9KIJ2QGboM

**Comment by usirin** [comment]
this is not happening with `nse` do you think we should close this?

/cc @gokmen

**Comment by gokmen** [comment]
@usirin yes, we shouldn't worry about the existing issues on old stack editor. if it's not valid for nse we can close it.

**Comment by diclee** [comment]
Verify passed on sandbox, not reproducible on new stack editor.
