### ISSUE TITLE
New team default stack is added to a member's sidebar directly.

### ISSUE THREAD

**Issue by diclee** [koding/koding#11023]
## Current Behavior
![gif](http://g.recordit.co/SD1YLchVmZ.gif)
http://recordit.co/SD1YLchVmZ

**Comment by diclee** [comment]
Also, after reinitializing default stack, old team stack is kept on sidebar as a draft although member cannot even initialize or clone it:
![gif](http://g.recordit.co/ZdsDlzVQL0.gif)
http://recordit.co/ZdsDlzVQL0

**Comment by gokmen** [comment]
This is something trivial, once an admin sets a stack template as default for the team it'll be shared with the team first then it'll be assigned as default stack template in team settings which will allow koding app to realize and generate that stack on the first load of new members or the existing members via the notification. So, having them visible in the sidebar once it's set as default is fine but for members we're not allowing to initialize a team stack while they have the old one and the flow fails on initialize request for this stack template. The simplest solution would be using the reinitialize flow on such stack template initialize request.

**Comment by diclee** [comment]
Verify passed on sandbox.
