### ISSUE TITLE
kd/machine: add config set/get commands

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#11062]
The command will update jMachine via remote.api, e.g. to make the following possible:

```
$ kd machine <label> config set meta.alwaysOn true
```

**Comment by rjeczalik** [comment]
@gokmen I'd want to make it possible to update JMachine.meta.alwaysOn via remote.api - could it be possible to add `POST /remote.api/JMachine.updateMeta/{id}` that could do that? (If we do that we may also want to prevent important meta fields - like meta.type - from being updated.)

**Comment by rjeczalik** [comment]
@gokmen Turned out`ComputeProvider.update` requires also a credential, so I'm sending one I retrieve from JMachine.one call beforehand.

**Comment by gokmen** [comment]
@rjeczalik right, forgot to mention. I'm using the first available one in the stack or the machine's credential in that case; https://github.com/koding/koding/blob/master/client/app/lib/providers/computecontroller.coffee#L647
