### ISSUE TITLE
kd/mount: check performance problems when accessing large git repositories

### ISSUE THREAD

**Issue by ppknap** [koding/koding#11064]
Apparently, git index algorithm detects file attributes set by mounts as not consistent with these stored in .git/index file. This causes git to read all files inside repository and compute SHA-1 sum for each of the files.

The goal of this issue is to make git diff detection algorithm happy with file attributes set by mounts. Some reading about which file attributes git index checks is [here](https://www.kernel.org/pub/software/scm/git/docs/technical/racy-git.txt) 

## Expected Behavior
Git doesn't have to compute SHA-1 sum of each file in mounted repository.

## Current Behavior
It does.

## Possible Solution
Add/modify inode attributes to match these stored in git.

## Steps to Reproduce (for bugs)
Mount git repository, access and run `git status`.

**Comment by rjeczalik** [comment]
Afair last resolution was to cache inode indexes within our index, correct?

Do you know why git may be not updating the inodes in its own index? If it did, second and later git commands would run faster, correct?

Even if I run git status multiple times, it always takes around 16s to complete.

What are the latest plans of improving the times?

[![rec](https://asciinema.org/a/2ivvgc1zx1m45h0o80dq9wv7p.png)](https://asciinema.org/a/2ivvgc1zx1m45h0o80dq9wv7p)

**Comment by ppknap** [comment]
@rjeczalik what is the output after:

```sh
$ git ls-files --debug > before
$ # time for git status
$ git ls-files --debug > after
$ diff before after
```

If there is no diff, this means that this issue is not related with git (or just git travels the entire tree which is fuse performance problem)

**Comment by gokmen** [comment]
@ppknap here https://gist.github.com/gokmen/8b7725671232b9d4303f14a8c452c534

**Comment by rjeczalik** [comment]
Also:

1) kd mount ls -> events queued = 0
2) cd mount; git status
3) kd mount ls -> events queued = over 9000

http://recordit.co/YjQH7XynRN

**Comment by ppknap** [comment]
@gokmen thanks! 🥇 Since Inode is changed (our FUSE sets it), git detects this as [file change](https://github.com/git/git/blob/027a3b943b444a3e3a76f9a89803fc10245b858f/read-cache.c#L120) which triggers SHA-1 sum on each file content which is obviously slow.

@rjeczalik yes, git must have triggered fuse to send "update" event on each file it examines. This should not happen on pure reads so either git writes to the files (very unlikely) or it called setAttributes which also triggers update events.
