### ISSUE TITLE
kd/mount/fuse: add support for symlinks inside mounted volume

### ISSUE THREAD

**Issue by ppknap** [koding/koding#11066]
It should be possible to use links inside mounted directories. This PR requires:

Considering remote path as `/remote` and mount point as `/mount`
- [ ] when transferring symlinks that are inside mount path, the mount path prefix should be stripped: remote link `/remote/A` should be stored as link node `A`.
- [ ] when transferring symlinks that are not inside mount path, these Nodes should be removed:
remote link `/non_remote/A` should be removed from the tree.
- [ ] it should be possible to have symlinks on local to any filesystem:
local symlink `/non_mount/A` should be stored as `/non_mount/A`. So that logic from (1) will work.
- [ ] tree nodes should have types: eg symlink, fifo, socket etc.

## Expected Behavior
It should be possible to safely use and create symbolic links iside mounted directory.

## Current Behavior
Symlinks are not implemented.

## Possible Solution
Described above.

**Comment by rjeczalik** [comment]
Closed by https://github.com/koding/koding/pull/11186.
