### ISSUE TITLE
kd/list: listed machines should be within team-scope only 

### ISSUE THREAD

**Issue by ppknap** [koding/koding#11074]
It's also possible to make `kd list` print only machines from currently used team & with `--all-teams` option that returns all machines.

**Comment by rjeczalik** [comment]
Changing scope of this issue. Todo is to make current implementation scope the machines to the current team.

The https://github.com/koding/koding/issues/10867 and https://github.com/koding/koding/issues/10866 are going to make the scoping obsolete, as remote.api does the scoping itself.
