### ISSUE TITLE
kd/mount: syncing does not start after a successful mount

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#11135]
kd/mount: syncing does not start after a successful mount

## Steps to reproduce
[![asciicast](https://asciinema.org/a/aihe97ig13vm5bsg6h696uiov.png)](https://asciinema.org/a/aihe97ig13vm5bsg6h696uiov)

### Signature
```
2f726a65637a616c696b2f31336430303064382d663136612d343330312d613936332d3334626134636364336636342f6275672f363838356366383439393366383033333137383766616162616637353363663461383731623861652e6a736f6e2e677a2e30
```

**Comment by rjeczalik** [comment]
Afterwards the sync deleted files which were not in the working three (`node_modules/` etc.).

**Comment by rjeczalik** [comment]
Using the `git` strategy all the files were queued for syncing (106111), after 1h there were still around 80k to sync.

Using the `all` strategy files were synced in 13min with no syncing needed - https://asciinema.org/a/737kjps13y3llmepvkvfgnfyk.

**Comment by ppknap** [comment]
Done by #11141
