### ISSUE TITLE
GCE Error

### ISSUE THREAD

**Issue by billyprice1** [koding/koding#11258]
i copy all of my json file to gce koding and it says We couldn't verify this credential, please check the ones you used or add a new credential to be able to continue to the next step.
 project id is right and that i dont know why

**Comment by ppknap** [comment]
Hey @billyprice1 !

Could you post here the content of your JSON file(removing any sensitive data of course)?

**Comment by billyprice1** [comment]
i just downloaded the json file from google cloud 

  "type": "service_account",
  "project_id": "ibillymedia",
  "private_key_id": "",
   "private_key":  , 

and all the rest of the file i just copyed all of it

**Comment by rjeczalik** [comment]
@billyprice1 Was your problem resolved? I'm closing this for now unless you confirm it still does fail for you. If it does, please provide me with your Koding's username and team name.
