### ISSUE TITLE
Change avatar is not working

### ISSUE THREAD

**Issue by cansirin** [koding/koding#11394]
## Current Behavior
http://recordit.co/GT840488i4

## Steps to Reproduce (for bugs)
1.join to any team
2.try to change your avatar

**Comment by hakankaradis** [comment]
cc: / @cansirin @usirin 
I have tested in both production and dev environment but couldn't reproduce

dev env: http://recordit.co/PKVhYPF7GQ
prod: http://recordit.co/fOQxQEUq19
