### ISSUE TITLE
Uing the provided curl command I geterror installing "Koding account": kloudError: Not Authorized (error code: 416)

### ISSUE THREAD

**Issue by leonormes** [koding/koding#11468]
## Current Behavior

I have copied the KD install script from my account. I run it in my terminal but when it gets to the sign in part I get `
Error: error installing "Koding account": cannot authenticate user: otaToken '8b0ddc93' is not validated; err: not found (b5fce8880707ee6b)`

## Steps to Reproduce (for bugs)
I can't give you my access key to try it out!

1.
2.
3.
4.

## Context

I am trying to have a folder on my computer that is synced via koding to other computers I work on. 
## Your Environment

I have tried this on both my iMac and a Linux machine and get the same problem on both.

**Comment by rjeczalik** [comment]
> Error: error installing "Koding account": cannot authenticate user: otaToken '8b0ddc93' is not validated; err: not found (b5fce8880707ee6b)

The token is one-time use only and most likely has already expired. You need to copy the link each time you want to perform installation.

**Comment by leonormes** [comment]
@rjeczalik Yes I do> I copy the link each time. I did something on the linux machine where I changed the config team name and it logged in but then came across a timeout problem when trying top mount a local folder. But that is another issue!

**Comment by rjeczalik** [comment]
Hey @leonormes, this problem should be already fixed on master, could you give it another try? Please reopen the issue if you encounter any more problems.
