### ISSUE TITLE
bootstrap-container: line 70: exec: configure: not found

### ISSUE THREAD

**Issue by MPNull** [koding/koding#11517]
## Current Behavior
```
docker-compose -f docker-compose-init.yml run init
```

Output:
```
/opt/koding /opt/koding
scripts/bootstrap-container: line 70: exec: configure: not found
```

## Possible Solution
https://github.com/koding/koding/pull/11504
Changes doesn't seems to be there. Made manual changes and it started working.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by timelf123** [comment]
How did you fix @MPNull ?

**Comment by MPNull** [comment]
https://github.com/koding/koding/pull/11504/files

Do these changes.

**Comment by timelf123** [comment]
Thank you

**Comment by sougat818** [comment]
I had the same issue and making those changes fixed it. Just wondering why this hasn't been merged.
