### ISSUE TITLE
Smart KD Mount Recommendation

### ISSUE THREAD

**Issue by tevirgen** [koding/koding#8186]
**Goals**
To improve the mounting UX via a simple `kd mount` style UX

**Why**
The settings for mounting can be a bit non-obvious to the end user, Devrim wanted to simplify that UX

**Acceptance Criteria**
- [ ] Does KD recommend you the available options without waiting for you to specify anything?
- [ ] Does it check the available space on the local drive?
##

**Comment by ppknap** [comment]
Superseded by new mounts and partially by #10714
