### ISSUE TITLE
Participated Team list feature set

### ISSUE THREAD

**Issue by gokmen** [koding/koding#8332]
- [x] Provide list of teams that I'm part of once I logged in to any of my team
  - [x] Backend requirement (https://github.com/koding/koding/pull/7883)
  - [x] Tests needs to be written
  - [x] Design
  - [x] UI implementation

---

- [x] Provide list of teams that I'm part of by email when I provided it from landing page
  - [x] Backend requirement
  - [x] Tests needs to be written
  - [x] Email Design
  - [x] Landing page implementation
 

ref: https://koding.atlassian.net/browse/TMS-3044

**Comment by diclee** [comment]
Email with the list of participated teams cannot be received. @alex-ionochkin can you please look at it to see if anything is wrong with backend requirements or it's a problem about the email service.

**Comment by alex-ionochkin** [comment]
@diclee, it works fine for me on sandbox. I was able to receive correct email after requesting it on https://sandbox.koding.com/Teams/FindTeam. Can you check it once again and make sure that email address is correct? If it still doesn't work for you, I'll check logs to understand the reason of the problem

**Comment by diclee** [comment]
@alex-ionochkin I've checked it again and it worked on latest but not on sandbox. I'm closing the issue since it's working on latest (will work on production as well). Can you please check sandbox again when you have time?
