### ISSUE TITLE
Fix Build Stack Error Modal Styling

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#8346]
![image](https://cloud.githubusercontent.com/assets/8261892/16670972/c8d1f858-4451-11e6-8f1b-0e6326f8ad7c.png)

[Error Modal.pdf](https://github.com/koding/koding/files/353117/Error.Modal.pdf)

**Comment by diclee** [comment]
Not valid anymore with the new build stack modal. Closing the issue.
