### ISSUE TITLE
Run mongo service based on official image

### ISSUE THREAD

**Issue by szkl** [koding/koding#8486]
mongo service is built in-repository [install/docker-mongo/Dockerfile](https://github.com/koding/koding/tree/master/install/docker-mongo). This should be replaced with [official image](https://hub.docker.com/_/mongo/) from [Docker Hub](https://hub.docker.com) to eliminate a step from running koding. Data population should be done via a migration.
##

**Comment by cihangir** [comment]
https://github.com/koding/koding/pull/9291
