### ISSUE TITLE
use kd link for installing klient on connected vms

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8514]
Currently we use the following link to install klient on user vms:

```
curl -sL https://kodi.ng/s | bash -s 629a9f26
```

Since we disabled auto-updates for managed klient due to kd mount issues, user has no mean to update klient on his connected vm.

We should instead use regular kd link for connecting vm:

```
curl -sL https://kodi.ng/c/p/kd | bash -s 17ec2083
```

Which will also install kd and make it possible to `sudo kd update`. We would also have only one way for installing klient which will greatly reduce maintenance cost.

~~We should also ensure a managed klient installed via kd link shows up on the sidebar, I've tested it on current production and it does not show up.~~ It shows up, I was not patient enough.

In the long term we should enable the auto-updates. (/cc @leeola)
##

**Comment by rjeczalik** [comment]
connected vm link does not work for ubuntu `16.04`, using kd link instead would have fixed that

**Comment by gokmen** [comment]
so, will kd installer provide the same functionality with klient installer? I mean will it start running klient and register the machine to kontrol automatically? or do user need to do something else after installation?

**Comment by rjeczalik** [comment]
Right both kd and klient installers do the same - they both register machine to kontrol and start klient. The only difference is that no managed jMachine doc is created for klient kontrol (as there's no managed machine modal for kd that does this I guess).

I'm going to rework machine registration with https://github.com/koding/koding/issues/8548, so taking the opportunity I could also make kontrol insert managed jMachine doc so user machine shows on the sidebar. This way separate "connected machine" or "your own machine" modal becomes obsolete. Moreover we have only one way of installing klient.

wdyt?

**Comment by gokmen** [comment]
That would be perfect, we shouldn't provide two different ways to install same thing. Add your own machine modal was doing the check on kontrol to get the latest register machine that we still may need to update the machine list or we can send a notification to trigger reload for machines otherwise they won't see the machine on their sidebars until they reload.

**Comment by gokmen** [comment]
Should I update the installer link to use the proposed one? Will it work as expected for now or do I need to wait for your updates on that?

**Comment by rjeczalik** [comment]
Probably you'd need to wait, since right now installing kd won't make your vm appear in sidebar (I guess there's no manage doc created?).

What kind of relationships do we need in mongo in order to make a vm appear in sidebar under the Managed VMs?

**Comment by gokmen** [comment]
We can still use the existing modal for that request but we will provide kd installer instead so it should work as is (I assume) because currently that modal is querying kontrol and if founds a new machine then it requests from backend to create the `JMachine` document. 

No relationship is required only requirement is that the users list of `JMachine` document needs to be proper for the active user and group.

**Comment by rjeczalik** [comment]
> modal is querying kontrol and if founds a new machine then it requests from backend to create the JMachine document.

So if we just replace the link with the kd one it'll work out of the box and no need for kontrol to create jMachine docs, correct?

**Comment by gokmen** [comment]
@rjeczalik yes, if that kd install scripts registers the machine we're good to go.

**Comment by rjeczalik** [comment]
Let's do this 🎉

**Comment by gokmen** [comment]
👍  will do that next week first thing.

**Comment by leeola** [comment]
I think the "Koding Connector Service" debian package is having issues with Ubuntu 14 now, lots of error cases. Can we bump this up in priority?

Also, @rjeczalik do you think #8935 blocks this? I know you mentioned it, but what are your thoughts?

**Comment by rjeczalik** [comment]
The `kontrol.register` method should create a jMachine managed document with newly registered KD Daemon. This way we could get rid of connected VM modal and connect external vms just by installing kd.

/cc @gokmen

**Comment by gokmen** [comment]
@rjeczalik this is the only change required 

```diff
diff --git a/client/app/lib/providers/managed/addmanagedmachinemodal.coffee b/client/app/lib/providers/managed/addmanagedmachinemodal.coffee
index e47c8061f7..16d5c8e4a1 100644
--- a/client/app/lib/providers/managed/addmanagedmachinemodal.coffee
+++ b/client/app/lib/providers/managed/addmanagedmachinemodal.coffee
@@ -87,7 +87,7 @@ module.exports = class AddManagedMachineModal extends ContentModal
       then "export KONTROLURL=#{KodingKontrol.getKontrolUrl()} CHANNEL=devmanaged; "
       else ''

-    cmd = "#{kontrolUrl}curl -sL https://kodi.ng/s | bash -s #{token}"
+    cmd = "#{kontrolUrl}curl -sL https://kodi.ng/c/p/kd | bash -s #{token}"

     @loader.destroy()
```

but we do have a weird error with installer;

```
Installing "KD"...

    Current version: -
    Latest version: 0.1.108

error executing "install" command: error installing "KD": open /usr/local/bin/kd: text file busy
```

so, I couldn't try it out for the rest of the flow.

**Comment by gokmen** [comment]
@rjeczalik can you check this out again? ^^

**Comment by rjeczalik** [comment]
@gokmen Do I need to do anything special to reproduce it? I've just tried the new url and [it works](https://gist.github.com/rjeczalik/edfc6c768b61528743171d39576b654d).

**Comment by gokmen** [comment]
if it's working then we can apply the patch I provided and close the issue I believe.
