### ISSUE TITLE
credentials: display detailed error message

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8518]
The `kloud.authenticate` response contains an error message for each credential which failed to authenticate.

Display it to the user to avoid cases like: https://koding.slack.com/archives/support/p1469129876000095
##

**Comment by hakankaradis** [comment]
![](https://monosnap.com/file/Hcotvf2BU7V5D1OLpWHQDdD0GyeLDe.png)
![](https://monosnap.com/file/rUQZN7mRnckndf8OGtnMRPMCLHUUop.png)

We are already showing error to user once credential fails.
@gokmen is it different error message that you meant?

**Comment by rjeczalik** [comment]
@hakankaradis For each validated credential we attach also a detailed error:

```
(rjeczalik-osxpro.local) ~ $ cat xd | jq
{
  "error": null,
  "result": {
    "f42560288446e4a995d0e2b9d5b8cefa": {
      "verified": false,
      "message": "no kites availabile"
    }
  }
}
```

In majority of cases the `no kites available` would be the most common cause for a failed credential.

The error means the kd daemon is not running and should be investigated / turned on (kd status). You may want to translate that particular error to something more user-friendly or create some Q/A docs with most common credential auth failures.
