### ISSUE TITLE
Loading animation should be displayed until the KD script is loaded on Koding Utilities page.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8528]
![gif](http://g.recordit.co/vJGGEDh8Gz.gif)
http://recordit.co/vJGGEDh8Gz

**Comment by diclee** [comment]
This issue is not resolved properly. Reopening it. 
http://recordit.co/kHAupyviv2

**Comment by gokmen** [comment]
as a side note, I didn't check it out but I don't know why we are waiting so much there, @hakankaradis can u investigate that one as well?

**Comment by hakankaradis** [comment]
sure @gokmen

**Comment by hakankaradis** [comment]
@gokmen I made my investigation, we were making request to fetch ota token in componentWillMount lifecycle, I move this call to utilities index.coffee to make this call early and I store them. I dont think it made huge difference but at least and I think it is in right place.

**Comment by gokmen** [comment]
@hakankaradis hmm, that token needs to be recycled so we need to make the call each time which means where it stays might be the correct place, let's check it out why the otatoken generation takes that much time.

**Comment by diclee** [comment]
Verify passed on sandbox.
