### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by usirin** [koding/koding#8601]
Right now current `Readme.md` is pretty outdated. We need to go over all the sections, remove unnecessarry ones and add new ones where it's seen necessary.

/cc @koding/developers

**Comment by usirin** [comment]
- Create a new section called `Folder Structure` and group initial sections of the Readme over there.
- Create a new section for communication channels/badges.
- Create a section for requirements.
- Create a quick start guide; what commands i should run to get my own `koding` instance running after cloning the repo?
- Create a section on running the required minimum db migrations, and include a link to an article about how `migrations` work.
- Move all deployment specific information under `Readme.deployment.md` or `wiki`.
- Keep the basics of the current `Logging` section, include a link to an article about how `Logging` works.

How does it look?

**Comment by cihangir** [comment]
I think we can use [Wiki](https://github.com/koding/koding/wiki) section, it supports nesting, version control, contribution etc. 

ie, Netflix organization has so many good examples 
https://github.com/Netflix/Hystrix/wiki
https://github.com/Netflix/atlas/wiki

**Comment by usirin** [comment]
Yeah, with an offline discussion with @gokmen we decided to include these in readme, and move all other details onto wiki.

- Communication Channels
- Try with Docker
- Installation
- License
- Contributing
