### ISSUE TITLE
Implementation of the new design for 'Security' section when 2FA is enabled

### ISSUE THREAD

**Issue by diclee** [koding/koding#8605]
_current version_
![image](https://cloud.githubusercontent.com/assets/8261892/17160102/48f338a8-5357-11e6-9f13-b0a6b1a2a74d.png)

- requires new design from @ftasdelen

**Comment by ftasdelen** [comment]
[Authentication Cancellation 02.pdf](https://github.com/koding/koding/files/386951/Authentication.Cancellation.02.pdf)

Sketch file is here: https://drive.google.com/open?id=0B2MBJBlRnx3xbzNTclBNT0dvbTQ

@diclee @hakankaradis

**Comment by diclee** [comment]
Verify passed on sandbox.
