### ISSUE TITLE
wrecker page is private

### ISSUE THREAD

**Issue by VikramTiwari** [koding/koding#8608]
The link from readme to wercker is private.

Link: https://app.wercker.com/#applications/53cd92eedabd120e390b36bd

Is this supposed to be so? If yes, then shouldn't have that logo in Readme. Otherwise this should be public as well.

PS: Great job on Koding and making it opensource. Kudos! 👍  💯

**Comment by gokmen** [comment]
Hi @VikramTiwari it's Koding Developers only for now but we will make it public soon. We'll update the README with #8601 I'll include that change as well, thanks for heads up!
