### ISSUE TITLE
kloud/userdata: create .ssh on behalf of user

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8619]
In order to inject a public key, known host etc. one needs to init .ssh directory in a template like:

```
        export SSH_DIR="/home/${var.koding_user_username}/.ssh"
        mkdir -p $SSH_DIR
        touch $SSH_DIR/authorized_keys
        chown -R ${var.koding_user_username}:${var.koding_user_username} $SSH_DIR
        chmod 700 $SSH_DIR
        chmod 600 $SSH_DIR/authorized_keys
```

If we move that part to be always executed before user_data, we'd spare a few lines on each template.

/cc @szkl @cihangir wdyt?
##

**Comment by cihangir** [comment]
sounds good to me

**Comment by szkl** [comment]
:+1:

**Comment by rjeczalik** [comment]
Superseded by https://github.com/koding/koding/pull/10935#issuecomment-291155988.
