### ISSUE TITLE
Discuss and Remove Add Packages Page in Stack Setup Guide

### ISSUE THREAD

**Issue by sibblegp** [koding/koding#8646]
![screenshot 2016-07-28 16 40 29](https://cloud.githubusercontent.com/assets/1026474/17233125/0ffde21e-54e2-11e6-8f79-bb0065df7c6a.png)

I've had many users get confused by this page thinking that these are the only things they can install with Koding.  I just had a customer get confused about this asking if they can have their software added to "our potential install list."  It also changes the stack template so that the user_data area has less comments in it compared to skipping the guide and makes it less clear that it is a bash area you are supposed to edit.  Devrim and I discussed some yesterday and he sees little to no value in this step of the guide.  I think we should just remove this step in the guide.

What are you thoughts?  @gokmen @sinan @rjeczalik @szkl Thanks!

**Comment by gokmen** [comment]
yes, we can remove it for now I don't see any value but confusion.

**Comment by szkl** [comment]
Sounds good to me.

**Comment by sibblegp** [comment]
Discussed and figured out.  Thanks everyone!
