### ISSUE TITLE
Implementation of new design for 'add server page' for create stack wizard

### ISSUE THREAD

**Issue by diclee** [koding/koding#8657]
@ftasdelen is working on the new design.

see discussion here: #8646

**Comment by hakankaradis** [comment]
@ftasdelen what is the latest status for this?

**Comment by ftasdelen** [comment]
[Create Stack Modal Update 07.pdf](https://github.com/koding/koding/files/514832/Create.Stack.Modal.Update.07.pdf)

We need @sinan 's review/approval on this.

**Comment by sinan** [comment]
pls change:

---

#### Select VMs for your stack.
Please select or/and add new VMs to your stack. You can update them later.

---

to

---

#### Specify your VMs for this stack.
You can create multiple VMs and add their default configuration.
You can also edit these later in the stack editor.

---

**Comment by ftasdelen** [comment]
[Create Stack Modal Update 07_1.pdf](https://github.com/koding/koding/files/514926/Create.Stack.Modal.Update.07_1.pdf)

I have updated the copy. Can you check it out last time?

**Comment by ftasdelen** [comment]
[Create Stack Modal Update 07_1.pdf](https://github.com/koding/koding/files/514930/Create.Stack.Modal.Update.07_1.pdf)

I have updated the copies and line spacing there. Can you check it out last time?

**Comment by devrim** [comment]
this feature is no longer required, we only let selection of provider, rest is going to be text based and stencils cc: @gokmen @sinan

**Comment by gokmen** [comment]
wizard part is completely removed as @devrim pointed out, closing this one.
