### ISSUE TITLE
An issue with starting docker-deamon

### ISSUE THREAD

**Issue by f** [koding/koding#8662]
The server does not start. But there's no error output. No idea what is wrong 😕 

```
$ docker-compose up -d
Starting kodingdockercompose_redis_1
Starting kodingdockercompose_mongo_1
Starting kodingdockercompose_rabbitmq_1
Starting kodingdockercompose_postgres_1
Starting kodingdockercompose_koding_1

fka at volant in ~/Code/koding-docker-compose on master
$
```

**Comment by szkl** [comment]
Hello @f, could you run without `-d` option? That would make koding services work at foreground and print all outputs.

**Comment by szkl** [comment]
Please reopen this if you still experience any issue.
