### ISSUE TITLE
'Keep Rocking' button on success modal for onboarding items does nothing.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8683]
![image](https://cloud.githubusercontent.com/assets/8261892/17328468/9c97f808-58c6-11e6-90e9-3f77fca80b62.png)
There are a few issues about this:

- [x] The button should close the modal. 
- [x] It doesn't seem right when it's displayed on the build stack modal. Because stack modal is centered in IDE but success modal is not. We need to have it centered in IDE.
- [x] Also, is this the correct size for modal @hakankaradis? It seems different than the design.
- [ ] Styling is not loaded in some cases and modal is displayed as below image:
![image](https://cloud.githubusercontent.com/assets/8261892/17331283/e6c43b74-58d2-11e6-9c8f-77ba4059ec27.png)
- [x] It's reappearing after logging in again.

**Comment by diclee** [comment]
@hakankaradis styling issue is still reproducible: 
![image](https://cloud.githubusercontent.com/assets/8261892/17441551/38de15a6-5b3a-11e6-9d28-e239c274b9a7.png)
Also, 'Keep Rocking' button needs clicking twice in order to work.

**Comment by hakankaradis** [comment]
@diclee this will be fixed with this pr #8781

**Comment by diclee** [comment]
Verify passed on sandbox.
