### ISSUE TITLE
'Leave Shared VM' modal has collaboration related text and needs to be updated.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8689]
![image](https://cloud.githubusercontent.com/assets/8261892/17342908/f2f69bae-5903-11e6-8504-4ab2aa05628b.png)

**Comment by usirin** [comment]
I am gonna assign it to @cansirin but, what should copy be?

**Comment by diclee** [comment]
I don't remember the exact copy but we can leave as it was before updating the modal style. Or a new copy like 'This will remove the shared VM from your sidebar. And you won't be able to have an access unless you're invited again.'  @sibblegp may have a better suggestion.

**Comment by sibblegp** [comment]
"This will remove the shared VM from your sidebar.  You won't be able to access it unless you are invited again."

**Comment by diclee** [comment]
Verify passed on sandbox.
