### ISSUE TITLE
Unnecessary horizontal scrollbar is displayed on 'Koding Utilities' for admins/owners.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8707]
## Expected Behavior
Horizontal scrollbar shouldn't be displayed.

## Current Behavior
![gif](http://g.recordit.co/iGPyXcikZa.gif)
http://recordit.co/iGPyXcikZa

## Your Environment
Mac OS X / Chrome - Version 51.0.2704.106

**Comment by hakankaradis** [comment]
@diclee I couldn't reproduce 
Here is the screencast for my evaluation
http://recordit.co/WJ2Y3dQOGK

**Comment by diclee** [comment]
I've tried on a new team on latest and sandbox and still can reproduce the issue. Can you also try on sandbox or latest @hakankaradis?

**Comment by hakankaradis** [comment]
I believe  #8659 will solve this problem as well.

**Comment by diclee** [comment]
Fixed with #8659. Closing the issue.
