### ISSUE TITLE
'Koding Button' section on Koding Utilities is broken.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8708]
## Current Behavior
OFF:
![image](https://cloud.githubusercontent.com/assets/8261892/17384798/1e920580-59e7-11e6-80c8-ce21457eae27.png)

ON:
![image](https://cloud.githubusercontent.com/assets/8261892/17384818/3e7abb30-59e7-11e6-8f39-b07ecfa7ac7a.png)

**Comment by hakankaradis** [comment]
@diclee I couldn't reproduce this bug
Here is the screen cast for my evaluation. 
http://recordit.co/TVW9A8lnDp

Is there any flow to reproduce this bug?

**Comment by diclee** [comment]
There's not any specific steps to reproduce it. 'OFF' state is the one just displayed when I switched to 'Koding Utilities' tab and the 'ON' state is the one  displayed when I just enabled it. I've tried both on sandbox / latest environments and Chrome / Safari browsers. Can you also try on sandbox or latest @hakankaradis?

**Comment by hakankaradis** [comment]
@diclee I believe #8659 fixed that problem, do you know that it is in sandbox?

**Comment by diclee** [comment]
Fixed with #8659. Closing the issue.
