### ISSUE TITLE
'Reinitialize Stack' modal should be updated to emphasize data loss.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8727]
## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/17433141/a2f40d08-5b0b-11e6-8a9d-51674fb0e8f1.png)

@ftasdelen can you please share the final design here?

@hakankaradis can you please fix a minor typo while updating the modal? (update `loose` as `lose`)

**Comment by hakankaradis** [comment]
@diclee Is there anything that I can do for this pr? I already updated the minor typo
