### ISSUE TITLE
client: building stack hangs on "Installing software..." step

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8743]
After stack was successfully built, the modal hangs on "Installing software..." step. If page is reloaded - the modal is gone.

## Expected Behavior

It should not hang but return to webterm immediately.

## Current Behavior

It hangs until page is reloaded.

## Possible Solution

Make it not hang.

## Steps to Reproduce (for bugs)

1.  Run koding from master.
2. Build a stack.

## Context

![pic](http://g.recordit.co/QtdTaH6lyV.gif)

## Your Environment

Development environment, current master - 5ed1eb253e2dd330b8ac6b3762180de875fb3ace.

**Comment by diclee** [comment]
Verify passed on latest.
