### ISSUE TITLE
If you close 'share stack template' modal without selecting an option, you're stuck on stack editor even though the stack has been saved successfully.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8791]
A suggestion as a solution: "The button 'Initialize' should stay there to initialize stack and maybe we can dim the “make team default” button to give the sense that this was done successfully."

**Comment by alex-ionochkin** [comment]
I agree that `Initialize` button should stay there but I would keep `Make Team Default` button active since user may change their mind and make the stack template default for the team.

**Comment by diclee** [comment]
Verify passed on sandbox.
