### ISSUE TITLE
User see old stack template when she edit the stack template After reinitialize the stack

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#8793]
User sees old stack template after reinitialize the stack

## Expected Behavior
User should see newly edited information in his/her stack template

## Current Behavior
Editing stack template shows old information about stack

## Steps to Reproduce
1. Edit and Reinitialize stack
2. Edit Stack again and will see old stack template 
http://recordit.co/1mHQmJIwf4

**Comment by diclee** [comment]
Verify passed on latest.
