### ISSUE TITLE
Registration with 'Try on Koding' is not working with 'Invalid invitation code' error.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8814]
## Expected Behavior
New users should be able to register and login directly to a team when 'try on koding' is enabled.
## Current Behavior
![gif](http://g.recordit.co/XSrKglJHVk.gif)
http://recordit.co/XSrKglJHVk

**Comment by sinan** [comment]
can't reproduce this on dev environment.

**Comment by diclee** [comment]
@sinan maybe it was a temporary issue back then. It's working on sandbox and latest at the moment. Closing the issue.

**Comment by sinan** [comment]
👍
