### ISSUE TITLE
'Upload File Error' modal should be updated with the new styling.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8832]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/17692907/04ab36e2-63a5-11e6-895b-e220258a22d6.png)

**Comment by diclee** [comment]
@cansirin @hakankaradis this error is displayed but the files are uploaded anyways. It's not the expected behavior, right?

**Comment by cansirin** [comment]
@diclee,  the files won't be uploaded anymore if this error occurs.

**Comment by diclee** [comment]
Verify about the original issue passed on latest.
