### ISSUE TITLE
Incorrect font is loaded for teams login/signup pages.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8842]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/17713602/6cb32628-6404-11e6-9ae6-a60043563656.png)

**Comment by diclee** [comment]
Is this the correct font @sinan? Just checking to be sure.
![image](https://cloud.githubusercontent.com/assets/8261892/17747866/680ca458-64bf-11e6-8495-91e5d961d00f.png)

**Comment by sinan** [comment]
yes. This is Soleil, but soon will be changed to Proxima Nova with an updated design.

**Comment by diclee** [comment]
ok, then verify passed on sandbox & latest.
