### ISSUE TITLE
When members click on 'Update My Machines' button, they get 'Cannot read property 'setReadOnly' of undefined' error displayed on the console

### ISSUE THREAD

**Issue by diclee** [koding/koding#8858]
## Error log
![image](https://cloud.githubusercontent.com/assets/8261892/17772506/e6bde48c-6551-11e6-8976-cc92c7ea5f94.png)

![image](https://cloud.githubusercontent.com/assets/8261892/17772554/0f43e636-6552-11e6-9717-7b9b96ad69b6.png)

## Steps to Reproduce
1. Update the team stack
2. Click on 'Update My Machines' button on 'Stack Updated' modal from a member's account OR select 'Reinitialize' from stack menu
3. You'll get 3 'Cannot read property 'setReadOnly' of undefined' error displayed on the console

**Comment by hakankaradis** [comment]
fixed with #8868

**Comment by diclee** [comment]
Verify passed on latest.
