### ISSUE TITLE
When a member tries to edit team stack from 'team stacks' section on dashboard, he cannot close dashboard and keeps getting same warning displayed until reloading the page.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8859]
## Current Behavior
![gif](http://g.recordit.co/3PiuBSpT8e.gif)
http://recordit.co/3PiuBSpT8e

**Comment by usirin** [comment]
Edit option is hidden from `members` on sidebar in #8868

**Comment by diclee** [comment]
This issue is still reproducible.

**Comment by diclee** [comment]
Verify passed on latest.
