### ISSUE TITLE
After team stack is updated, member cannot update machines until reloading the page in some cases.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8861]
## Current Behavior
![gif](http://g.recordit.co/uruYMbsPp1.gif)
http://recordit.co/uruYMbsPp1

### Error Log
![image](https://cloud.githubusercontent.com/assets/8261892/17773507/7ecd33cc-6557-11e6-981a-fde9985d9051.png)
![image](https://cloud.githubusercontent.com/assets/8261892/17773534/a6dd40b4-6557-11e6-8b6a-63376cac94b6.png)

**Comment by diclee** [comment]
Not happening all the time but you need to reload the page in order to continue when it happens.

**Comment by usirin** [comment]
Fixed with #8795

**Comment by diclee** [comment]
Verify passed on latest.
