### ISSUE TITLE
After editing team stack, it's saved as another stack template in some cases.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8862]
## Expected Behavior
When you edit and save a team stack it should be updated, not saved as another stack template.

## Current Behavior
![gif](http://g.recordit.co/IwCbZ2T6Nk.gif)
http://recordit.co/IwCbZ2T6Nk

After reloading the page team stack's name is converted to the old one.
![image](https://cloud.githubusercontent.com/assets/8261892/17774078/5d442762-655a-11e6-83a0-d83f02702b0c.png)

It's happening on every second edit.

**Comment by usirin** [comment]
No matter what i did, i couldn't reproduce this neither on sandbox nor on local :/

**Comment by hakankaradis** [comment]
Me neither

**Comment by diclee** [comment]
This issue is not reproducible at the moment. Closing.
