### ISSUE TITLE
'URL shortener' for collaboration session link is not working.

### ISSUE THREAD

**Issue by diclee** [koding/koding#8865]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/17780015/7d798f82-6572-11e6-8f26-c56cb7d8d1e4.png)

**Error Log:**
![image](https://cloud.githubusercontent.com/assets/8261892/17780047/975e81fa-6572-11e6-8fec-50389e57fe71.png)
![image](https://cloud.githubusercontent.com/assets/8261892/17780085/b6e64986-6572-11e6-9826-dcc398052803.png)

You need to resize in order to view the 'End Collaboration' button.

**Comment by diclee** [comment]
I guess this was a temporary issue and resolved now. But it still may need further investigation in order to not happen again.

**Comment by usirin** [comment]
> I guess this was a temporary issue and resolved now. But it still may need further investigation in order to avoid from happening again.

Same happened for me as well, worked 100% of the times i've tried.

Closing.

**Comment by diclee** [comment]
Working correctly at the moment.
