### ISSUE TITLE
kloud/provider: expose cloud-init configuration in stack template

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8903]
Execution of `user_data` happens after the instance was provisioned with cloud-init. If user wanted to create a docker group and add themself it, doing so in `user_data` would require restart of a klient agent ~~and app refresh~~, which is not a good ux.

The problem would be gone if the group management was handled by cloud-init.

Quick solution would be to make it possible to configure groups via tf variable, e.g. `${var.koding_groups}`. [And overwrite the defaults here](https://github.com/koding/koding/blob/a3c7b67a28a3d01a3933bcff0604b0d1a600c6b0/go/src/koding/kites/kloud/provider/aws/stackplan.go#L118).

Full solution would be to make it possible for a user to take over cloud-init - so the user can provide their own cloud-init configuration. If `user_data` begins with `#cloud-config` line, we should parse the content and hook our - basically merge [our cloud-init](https://github.com/koding/koding/blob/a3c7b67a28a3d01a3933bcff0604b0d1a600c6b0/go/src/koding/kites/kloud/userdata/userdata.go#L92-L214) into user's one. Now we were doing other way round - embedding user's script into our cloud-init. The important bits of our cloud-init is kite.key, non-interactive sudo (klient's assumption) and installation of the klient itself. If by reworking cloud-init handling we'd also get rid of klient.deb and used the plain binary instead, we'd fix old-standing issue with stacks supporting only debian-based distrubutions.

Open for questions/discussion.

/cc @szkl @cihangir 
##

**Comment by cihangir** [comment]
Second one would be much better and generalized, plus easy to implement ( only coreos cloud-config could be problematic )

**Comment by szkl** [comment]
Sounds like a plan :+1:

**Comment by rjeczalik** [comment]
Done by https://github.com/koding/koding/pull/10677.
