### ISSUE TITLE
kd won't to start (always bound to 127.0.0.1)

### ISSUE THREAD

**Issue by CRACKBOY** [koding/koding#8919]
I'm trying to deploy Koding for local usage, everything works fine except kd Daemon that syncs my local environment to the remote one.
Here the full log: http://pastebin.com/1NHei5xD

**Comment by rjeczalik** [comment]
Hey @CRACKBOY 

The real problem here is klient not starting in your env - kd correctly tries to reach klient, which should be listening on `127.0.0.1:56789`.

Resolving the linked issue will solve your problem, so closing this one for now.
