### ISSUE TITLE
Consolidate klient installation methods

### ISSUE THREAD

**Issue by leeola** [koding/koding#8936]
In an effort to support multiple OSs, our installation method of klient and/or klientctl needs to be consolidated. Currently, the Stacks our installation method is a Debian file, then of course we have Koding Connector Service and finally Klientctl. Currently klientctl has the only multi-os installation support, so that is seems the most likely candidate.

cc @rjeczalik 
##

**Comment by rjeczalik** [comment]
Going to be taken care of via `kd daemon install` (#9886).
