### ISSUE TITLE
client: display verification error to the user

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8996]
Credential verification can fail due to numerous reasons - lack of vagrant installed on user box, wrong version or outdated klient binary.

Currently we display only generic "something went wrong" instead of displaying the actual error message, which would allow the user to fix the error.

Example:

![pic](http://i.imgur.com/5V6ONDd.png)

The https://github.com/koding/koding/pull/8993 enforces users to update klient. We'd need to display actual error message so the users know why the verification failed.
## Expected Behavior

The actual error message is displayed.
## Current Behavior

It is not.
## Possible Solution

Display it.
##

**Comment by rjeczalik** [comment]
@alex-ionochkin Can we close this?

**Comment by alex-ionochkin** [comment]
It's done but let's wait utill it's tested. I moved it to QA pipeline

**Comment by rjeczalik** [comment]
:+1:
