### ISSUE TITLE
Participant cannot join a collaboration session with the same link that he rejected once.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9009]
## Expected Behavior
User should be able to join with the same collaboration link after rejecting it once.

## Current Behavior
When a user tries to join with the same collaboration link, the shared machine or invitation is not displayed in the sidebar of the participant.
Same applies also for the participants that left the session or were kicked before.

**Comment by diclee** [comment]
It's reproducible only on sandbox.

**Comment by diclee** [comment]
It becomes reproducible also on latest.

**Comment by cihangir** [comment]
> User should be able to join with the same collaboration link after rejecting it once.

I am not sure this is a bug. Why would someone reject an invitation and still want to access? In normal cases, they should be re-invited.

@sinan wdyt?

**Comment by sinan** [comment]
Since we got rid of the invitation logic and only kept the link option to join a session, I think this is a valid issue.

**Comment by cihangir** [comment]
oh that is right, 
i dont remember the flow exactly anymore but this task might require backend development

**Comment by diclee** [comment]
I don't know what's changed but it's working as expected at the moment. Closing for now.

**Comment by diclee** [comment]
Verify passed on latest.
