### ISSUE TITLE
Realtime events for teammates section doesn’t work

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9022]
Teammates lists are not updated in realtime, after sending invitations, revoking any invitation, or changing member's role.
Problem is fixed after refreshing the browser

For example;
- sent an invitation: Where we create an invitation, we need to send it to group from backend
- revoke an invitation: Where we delete the invitation, we need to send it to group from backend
- Admin or owner changed the user's role: Where we changed user role, we need to send it to group from backend

## Pre-requirements

Coffeescript, React, Flux
## Expected Behavior

Teammates list should be updated in realtime.
## Current Behavior

Any changes in teammates section for member or admin will not be known by other teammates.
## Possible Solution

Check real time events for teammates changes.
## Steps to Reproduce (for bugs)
1. Login your team or create one if you don't have
2. Go to Dashboard modal from header of left hand side sidebar section
3. Go to My Team section and send an invitation
4. Login to your team as a member or admin in incognito or different brand browser. And open my team section for this browser as well.
5. Now you have 2 open different browser. You will see the teammates list will not be updated with sending new invitations or revoking existence invitation for either admin or member's browser.

http://recordit.co/CS2yTBdGzM 
## Your Environment
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 53, node.js 0.10
- Operating System and version (desktop or mobile): MacOSX 10.11
## Acceptance Criteria

The pull requests must:
- [ ]  have unit tests 
- [ ]  satisfy all issue requirements
- [ ]  have screencast or screenshot.

There is no partial acceptance
If something is not clear, discuss it below.

**Comment by hakankaradis** [comment]
related with #8866

**Comment by NodeUrsa** [comment]
Hi,
Now, Only I can see  on http://52.204.11.235:8090, not on domain.
it shows a error "unable to resolve host flyingleonardo99".
Please check it.

**Comment by hakankaradis** [comment]
Hello @NodeUrsa,
This question is not related with issue. If you have a questions regarding your dev environment, please use our slack [koding-dev](cebeci.koding.com/slackin/) channel

**Comment by hakankaradis** [comment]
Here you can find where we are taking action for those calls.
[Revoke invitation](https://github.com/koding/koding/blob/master/workers/social/lib/social/models/invitation.coffee#L106),     [Change Member Role](https://github.com/koding/koding/blob/master/workers/social/lib/social/models/group/index.coffee#L607),    [Accept invitation ](https://github.com/koding/koding/blob/master/workers/social/lib/social/models/invitation.coffee#L135)

**Comment by diclee** [comment]
Verify passed on sandbox.
