### ISSUE TITLE
kloud/client: add API for describing available providers

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9024]
Issue for desgining API for kloud, so it's possible to auto-plug new providers into the client.

/cc @gokmen

**Comment by gokmen** [comment]
I think we can define supported providers on configuration, instead of dynamically getting the list of providers on each request/load we can let them defined in the configuration and passed to client in payload. which can be handled part of this issue as well https://github.com/koding/koding/issues/9068 

wdyt? @rjeczalik

**Comment by rjeczalik** [comment]
@gokmen My initial though on this was that in order to make it possible to generate a client for provider it'd need to know three things:

- how the default template look like
- the bootstrap values schema, so it knows when to call bootstrap
- the credential values schema, so it knows how to generate credentials tab

I wanted to add `describeProviders` method, which would return the following payload:

```
[{
  "defaultTemplate": "...",
  "bootstrap": { schema },
  "credentials": { schema },
}]
```

The `schema` would be some type definition object - I was thinking about re-using Terraform schema; e.g. example schema for AWS credentials would look like:

```
{
  ...
  "credential": {
     "access_key": {
       "type": "string",
       "required": true,
     },
     "secret_key":  {
       "type": "string",
       "required": true,
     }
  }
  ...
}
```

I think it would be easier to have it implemented as API, since I could just generate the values, with configuration it'd would require manual maintenance (thus it won't be dynamic - e.g. you add support to kloud and you still need to write some configuration in order to make it work).

This is how I envision it, we can hook up on a call or something if this would require further design.

**Comment by gokmen** [comment]
what about keeping these definition objects as in provider folders and let both client side and kloud to read from there while booting up? all I'm trying to avoid making unnecessary calls to kloud on each load of the page to just get the pre-defined data.

**Comment by rjeczalik** [comment]
Wouldn't it be possible for a client to call kloud once during bootstrap and then keep the data cached in memory? If not, creating jProviders collection and updating it on kloud start would be enough?

**Comment by gokmen** [comment]
all these requires a data passing on each reload, even you keep in memory it will be vanished on client-side. we can do something like; support everything on client-side, toggle them based on the api response from kloud but which will again adds a repetitive calls to kloud. let's have a session for this tomorrow.

**Comment by rjeczalik** [comment]
After this issue is resolved the Schema types (Credential / Bootstrap) should be extended for the enum support.

The rationale: we're going to autogenerate frontend support for each of the provider, in order to do so any Credential or Boostrap value that is an enum (e.g. AWS instance_type) should implement the following interface (so we are able to generate value for the drop-down lists):

```go
type Enumer interface {
    Enum() []interface{}
}
```

For example the aws.Credential would look like:

```go
type Credential struct {
    AccessKey string   `json:"access_key" kloud:",secret"`
    SecretKey  string   `json:"secret_key" kloud:",secret"`
    Region       Region `json:"region"`
}

type Region string

func (Region) Enum() []interface{} {
    return []interface{}{
        "us-east-1",
        "eu-central-1",
        ...
    }
}
```

The `secret` option in kloud tag is needed to automatically shadow the variable, I'm going to move that code inside BaseProvider, for now there's no harm in adding it to existing type definitions.
