### ISSUE TITLE
Stack-Editor: New credential is added the bottom of credential section

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9059]
When user create new credential, it is added to bottom of credentials section.
We want to see this new credential at the top of this section.

After refreshing the browser credentials are sorted right.

## Expected Behavior
When user add new credential, it should be added to top of credentials section in stack-editor page.

## Current Behavior
New credential is added to bottom of credential section.

## Possible Solution
Check computeController's `CredentialAdded` event

## Steps to Reproduce (for bugs)
1. Go to credentials page in stack-editor
2. Create new credential
3. it is added to bottom of this section

**Comment by diclee** [comment]
Verify passed on sandbox.
