### ISSUE TITLE
Stack templates cannot be saved with 'Cloudinit template is not a valid YAML file' error.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9070]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/18685736/1e197c2a-7f2e-11e6-9b0a-01a0f371bd31.png)

**Comment by gokmen** [comment]
Fixed with https://github.com/koding/koding/pull/9065 waiting to deploy.

**Comment by rjeczalik** [comment]
Fixed & deployed.

**Comment by diclee** [comment]
Verify passed on sandbox.
