### ISSUE TITLE
Allow members to see stack scripts 'read-only'

### ISSUE THREAD

**Issue by usirin** [koding/koding#9078]
Members should be able to see stack scripts, right now there is no UI element redirects user there.

## Expected Behavior
- Members should see an option in the sidebar stack menu saying "View stack", and it will redirect them to stack-editor.
- Members should be able to click to stack name in dashboard to navigate stack editor.
- Stack editor should be 'read-only'.

## Current Behavior
- There is no menu option
- Stack names on dashboard are not clickable.

**Comment by diclee** [comment]
Verify passed on sandbox.
