### ISSUE TITLE
Postgres service check problem

### ISSUE THREAD

**Issue by johnnypea** [koding/koding#9083]
I tried to install Koding with the "docker-compose up" but the "koding" service ("koding/koding" container) crashes moments after starting.

I used this snippet:
```
git clone https://github.com/koding/docker-compose.git koding-docker-compose
cd koding-docker-compose
# Requires docker-compose version >= 1.6
docker-compose up -d
```

From the logs I found out a check for the "postgres" service is not successful:
```
postgres:--username - no attempt
error: postgres service check failed on postgres:
```

My versions:

> Docker version 1.12.1, build 6f9534c

> docker-machine version 0.8.1, build 41b3b25

> docker-compose version 1.8.0, build f3628c7
> docker-py version: 1.9.0
> CPython version: 2.7.9
> OpenSSL version: OpenSSL 1.0.2h  3 May 2016

> VirtualBox Version 5.1.6 r110634 (Qt5.5.1)

**Comment by szkl** [comment]
Hello @johnnypea. Could you try to fetch recent version of koding/docker-compose repository and try again? A new version of koding/koding image is pushed to fix this issue.

**Comment by johnnypea** [comment]
I can confirm it's working now. Thanks.
