### ISSUE TITLE
Email with confused empty team list is sent when user doesn't participate any team

### ISSUE THREAD

**Issue by alex-ionochkin** [koding/koding#9106]
## Expected Behavior

There should be a notification that user doesn't participate any team when they request a list of their teams
## Current Behavior

User gets email with content on the screenshot
https://uploads.intercomcdn.com/i/o/10765279/5f0efe779536acb7c92c7c88/IMG_0132.PNG
## Steps to Reproduce (for bugs)

Go to `/Teams/FindTeam` and request a team list for user who doesn't participate any team
##

**Comment by diclee** [comment]
Cannot verify this issue because all of my test users participate in at least a team. And currently registration of a new user is only performed while creating a team. Closing this issue. If it's reported again we can open and investigate further.
