### ISSUE TITLE
Add Clone option to MenuItem for Stack and Stack Templates

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9122]
We are going to give chance to user to clone any stack or stack template by using `clone` option in menu items modal.

## Expected Behavior
Admin or member will be able to clone any stack.
If member is not allowed to create stack by admin, they will not see clone option.

## Current Behavior
Admin or member has no option to clone stack

**Comment by diclee** [comment]
Verify passed on sandbox.
