### ISSUE TITLE
kloud/provider: add Google Cloud Platform (GCP) support

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9134]
Implement kloud provider for google cloud platform (gcp)

Example of custom kloud provide plugin
https://github.com/koding/kloud-provider-example

**Comment by sibblegp** [comment]
Just want to track this.

**Comment by rjeczalik** [comment]
While implementing this please take the following into consideration while designing schema types: https://github.com/koding/koding/issues/9024#issuecomment-250926522

**Comment by tboerger** [comment]
So I can get the bounty if I implement support for GCP? Sounds pretty interesting!

**Comment by hakankaradis** [comment]
@tboerger We are going to handle this issue in-house. We are having problem with bountysource.com so We couldn't remove the bounty tag. So please don't start the issue.

**Comment by tboerger** [comment]
> @tboerger We are going to handle this issue in-house. We are having problem with bountysource.com so We couldn't remove the bounty tag. So please don't start the issue.

That's sad... I really wanted to start it because of the bounty.
