### ISSUE TITLE
Stack-Editor: Undoing and Redoing on Stack template section is not working properly.

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9142]
Undoing or Redoing in stack template in stack-editor doesn't work properly.
Custom Variables and Read me pages should also be fixed.
## Expected Behavior

It should continue to undo until previously saved state.
User should be able to redo the changes
## Current Behavior

It continue to undo until make the stack template empty and redo doesn't work as well.
## Possible Solution

Saved stack template state should be stored to be able make comparison
## Steps to Reproduce (for bugs)
1. Go to Stack-Editor section by editing a current stack or create new one
2. Go to Stack template, custom variables or read me tabs
3. Press Command (Ctrl) + Z
4. You will see empty stack template
5. or write something then press Command + Z. it will continue to redo changes till see the template empty.
## Acceptance Criteria

The pull request must
- [ ] satisfy all requirements
- [ ] provide screencast
- [ ] satisfy [coffeescript style guideline](https://github.com/koding/styleguide-coffeescript)

**Comment by lionheart1022** [comment]
If you press the undo key just after opening stack-editor page, the content will be cleared even you don't change anything.
What I had to do is to fix that issue - the initial content should be there even the user press undo key continuously.
And the second issue was to make the redo key enable.
Now undo(command+z) and redo(command+shift+z) work well.

Please let me know if you more questions.
Thanks

**Comment by diclee** [comment]
Verify passed on latest.
