### ISSUE TITLE
Closing Welcome Modal redirect to wrong URL

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9143]
Closing Welcome modal cause the losing previous page because it is always redirected to `/IDE/...` url
## Expected Behavior

Closing Welcome modal should redirect user to previous page.
## Current Behavior

Closing Welcome modal always redirect user to `/IDE/` url
## Steps to Reproduce (for bugs)
1. Go to stack-editor page (by editing a stack template or create new stack)
2. Open welcome modal from sidebar header
3. Close the modal
4. You will be redirected to `/IDE/...` url

Here is screencast
http://recordit.co/3vXD1vSpuE

**Comment by diclee** [comment]
This issue is still reproducible on sandbox and latest: 
![gif](http://g.recordit.co/meds70Iylh.gif)

**Comment by diclee** [comment]
@hakankaradis this is the current behavior for closing the welcome modal. Is it the expected behavior?

![gif](http://g.recordit.co/COPK4eVZbe.gif)
http://recordit.co/COPK4eVZbe
