### ISSUE TITLE
Dashboard/Virtual-Machines: VM Power toggle comes disabled even the stack is built before

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9144]
`VM Power` toggle button comes disabled even the stack is built before.
Refresh doesn't solve the problem.

## Expected Behavior
If stack is built before user should on/off the machine from virtual machines section in dashboard

## Current Behavior
If the stack is not built before, the `VM Power` toggle button should come disabled. But now if the machine is not running, the `VM Power` toggle button comes disabled. 

## Possible Solution
Toggle states should be checked by looking stack status. Because when we switch `Always On` state to `On`, the `VM Power` toggle became enable.

## Steps to Reproduce (for bugs)
1. Create new stack template and build the stack
2. Turn the VM off
3. Go to Virtual machines section in dashboard (`/Home/Stacks/virtual-machines`)
4. You will see `VM Power` toggle disabled.

Here is the screenshot
![](https://monosnap.com/file/Vyavh2VPEEASHyoFdaM2lz95dD6kC4.png)

**Comment by hakankaradis** [comment]
Once we fix kloud info response, this issue will be fixed.

**Comment by hakankaradis** [comment]
fixes with #9190

**Comment by diclee** [comment]
Verify passed on sandbox.
