### ISSUE TITLE
Machine states are inconsistent while turning a VM on.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9156]
## Current Behavior
![gif](http://g.recordit.co/mWpTP2nGsC.gif)
http://recordit.co/mWpTP2nGsC

![image](https://cloud.githubusercontent.com/assets/8261892/18977263/9f3c567e-866d-11e6-83aa-b122d05e47a5.png)

**Comment by rjeczalik** [comment]
Already fixed by https://github.com/koding/koding/pull/9139.

**Comment by diclee** [comment]
Verify passed on sandbox.
