### ISSUE TITLE
Renaming filename from IDE

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9158]
When user click the `rename` button from either filetree or file menu. It should only focus filename with no extension.
- [ ] When clicking rename file name in ide will only focus filename with no extension

@ftasdelen
- [ ] Add icon to file and terminal see design  
- [ ] make the selected tabs obvious (blue bar) see design 
## Design Requirements

[IDE Icons.pdf](https://github.com/koding/koding/files/543190/IDE.Icons-1.pdf)
[icons.zip](https://github.com/koding/koding/files/543153/icons.zip)
## Acceptance Criteria

The pull requests must:
- [ ]  satisfy all issue requirements
- [ ]  have screencast or screenshot that proves you job.

There is no partial acceptance
If something is not clear, discuss it below.

**Comment by hakankaradis** [comment]
We are done with this feature, closing.

**Comment by diclee** [comment]
Verify passed on latest.
