### ISSUE TITLE
Update Build Stack Success Modal Design

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9159]
Implement new design for build stack success modal.
![](https://monosnap.com/file/hjS994uZVNy5ZiSp0p56RzrS1dzxdv.png)

- [ ] `View The Logs` button should redirect to Ide to show logs
 * see `Show Build Logs` button in Virtual machines section in dashboard 
- [ ] `Install` button should redirect to kd utilities
 * redirect to `/Home/Koding-Utilities/kd-cli`
- [ ] `Invite` button should redirect to invite team section 
 * redirect to `/Home/My-Team/send-invites`

**Comment by hakankaradis** [comment]
We are going to close this issue. We need to investigate more for UX
/cc: @sibblegp

**Comment by hakankaradis** [comment]
New update for this issue.
/cc: @sibblegp 
Please update the text if it is required @ftasdelen

**Comment by ftasdelen** [comment]
@alex-ionochkin I will have some design improvement on this.
@sibblegp Can you update the copies?

**Comment by ftasdelen** [comment]
![image](https://cloud.githubusercontent.com/assets/306264/19199792/a9b0387e-8c7a-11e6-87cf-102ac9a1d751.png)
The new layout is going to be this one.

PDF:
[new stack modal new success modal.pdf](https://github.com/koding/koding/files/516783/new.stack.modal.new.success.modal.pdf)

Sketch: https://drive.google.com/open?id=0B2MBJBlRnx3xLV9DejhuTENYVDA

cc @hakankaradis cc @sibblegp

**Comment by devrim** [comment]
@ftasdelen invite to collaborate flow should be updated as per our design meeting 10/6 cc: @sinan

**Comment by ftasdelen** [comment]
@alex-ionochkin i have updated the design file. You can see the behaviors on that file. "Start collaboration" button will be triggered automatically. After collaboration started, we will show a tooltip and explain how users can share the link we generated. We will also same functionality and behavior on this:https://github.com/koding/koding/issues/9169

cc @devrim

**Comment by diclee** [comment]
Verify passed on sandbox.
