### ISSUE TITLE
IDE/Editor: Design updates for `find/find & replace/search all files/Find file/Go to line` functionalities 

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9168]
In code base, There are already designs and functionalities for all search functionalities.
They all need to be changed with new design.
## Requirements
- Replace old designs with new one.
- Make sure the current functionalities are working.

[FindSearch.pdf](https://github.com/koding/koding/files/720627/FindSearch.pdf)

## Acceptance Criteria
The pull request have to prove that all search functionalities are working with new design.
- [x] Find
- [x] Find and Replace
- [x] Search in All Files
- [x] Find File by Name
- [x] Go to Line

/cc: @ftasdelen

**Comment by ftasdelen** [comment]
You can find the Sketch file here:
https://drive.google.com/open?id=0B2MBJBlRnx3xb1hELWs0TEFNbkE

**Comment by hakankaradis** [comment]
closing the issue, here is the pr #11133
