### ISSUE TITLE
Add new Functionalities to VM Boot Success Modal

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9169]
We need to add new functionalities to VM Success Modal.

![](https://monosnap.com/file/nhX0Z9nBG9msC5eHhh6ldKIm9XvCq9.png)
- [ ] Connect this VM to your local IDE
- [ ] Start collaboration now

We need a new design for this modal @ftasdelen

**Comment by ftasdelen** [comment]
![image](https://cloud.githubusercontent.com/assets/306264/19208253/e7b50636-8cac-11e6-9913-e6f935652d7b.png)

I have updated the design.

@sibblegp can you check it out please?

cc @hakankaradis

**Comment by sibblegp** [comment]
Why did we change from the vertical list?

**Comment by sibblegp** [comment]
"Use KD to connect the remote file system of your new VM locally on your system."

**Comment by ftasdelen** [comment]
@sibblegp the width of this modal is smaller than the stack success modal. So, it doesn't look good on here if we make it vertical.

**Comment by sibblegp** [comment]
Got it.

**Comment by ftasdelen** [comment]
@alex-ionochkin I have created a flow to show how the new interactions work:
[new VM success modal 03.pdf](https://github.com/koding/koding/files/534355/new.VM.success.modal.03.pdf)

"Invite" and "Install" interactions will be same with the stack build success modal.

**Comment by alex-ionochkin** [comment]
Thanks @ftasdelen! Could you please add a sketch file here so I can implement a new design on frontend?

**Comment by ftasdelen** [comment]
@sinan Does it look good?
