### ISSUE TITLE
Stack-Editor: Add Image Upload Feature to ReadMe section 

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9171]
Add upload image feature to readme section.
## Requirements
- [ ] Add upload link to bottom of readme section
- [ ] This link will be open a modal to give user chance to upload jpg, png or gif.
- [ ] The image's size must be between 2 kb and 20 MB otherwise show error message.
- [ ] The modals for upload image should be same with design file.
- [ ] Drag and drop feature should also be added.
## Acceptance Criteria

The pull request must
- [ ] satisfy all requirements
- [ ] provide screenshot for each modal and screencast for drag and drop
- [ ] satisfy [coffeescript style guideline](https://github.com/koding/styleguide-coffeescript)
## Design file

It is in comment.

If something is not clear, discuss it below.

**Comment by ftasdelen** [comment]
You can see the design and flow in the following PDF file:
[Readme Upload 05.pdf](https://github.com/koding/koding/files/549350/Readme.Upload.05.pdf)

cc @hakankaradis

**Comment by ftasdelen** [comment]
The Invision project is here:
https://invis.io/ZW8YNP4YA

The Sketch file is here:
https://drive.google.com/open?id=0B2MBJBlRnx3xRUZqOTdfSmFSc0E
