### ISSUE TITLE
KONFIG.version is incorrectly parsed as a number instead of a string.

### ISSUE THREAD

**Issue by ppknap** [koding/koding#9203]
KONFIG.version is constructed from the beginning of Koding's git repository SHA-1 HEAD string. In some cases JS can render it as a number instead of string. Eg:

SHA-1: `5205e1426514bb80027343f7a83e245764f468e4` is interpreted as `5.205e+145` instead of  `5205e142`. Thus, rendered template will contain links like:

``` html
<script src="/a/p/p/5.205e+145/bundle.js"></script>
```
## Expected Behavior

Rendered template contains valid version strings.
## Current Behavior

Rendered template contains version cast to a number and then to a string.
## Possible Solution

Explicitly cast KONFIG.version to string eg. [here](https://github.com/koding/koding/blob/master/workers/social/lib/social/render/scriptblock.coffee#L73)
## Steps to Reproduce (for bugs)

Use KONFIG with scientific-number-like version string. Eg. `1234e567`.
## Screenshots

![image](https://cloud.githubusercontent.com/assets/5021246/19130061/fb2083e4-8b49-11e6-8c81-e55787086c3c.png)

**Comment by szkl** [comment]
I think `koding-config-manager` module should be aware of `version` property. Therefore, `KONFIG.version` wouldn't have to be casted wherever referenced from.

**Comment by gokmen** [comment]
I remember that we've solved this problem like @szkl said. Dunno when/why we've reverted that change :|

**Comment by szkl** [comment]
@gokmen IIRC that bug was in `client/`.

**Comment by ppknap** [comment]
@szkl if you are going to work on this, could you please add also:

```diff
diff --git a/configure b/configure
index 08cb7e8..5d4f201 100755
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/usr/bin/env coffee
-argv = require('minimist')(process.argv.slice(2))
+argv = require('minimist')(process.argv.slice(2), opts={"string": "version"})
 log = console.log
 fs = require 'fs'
 os = require 'os'
```

slightly related, but I noticed the same bug when I was passing custom version string to "./configure".
