### ISSUE TITLE
IP address is displayed as '0.0.0.0' even though the VM is on.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9219]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/19173907/c53bb762-8bdf-11e6-8e27-f5e58af90c95.png)

**Comment by gokmen** [comment]
@rjeczalik can this be a change in naming? like `ipAddress` -> `ipaddress`? didn't check out the issue, just a guess.

**Comment by rjeczalik** [comment]
> can this be a change in naming?
@gokmen Yes, that's was the issue with case combined with not returning kite's registerURL after successful dialling in one place. Sent PR.

**Comment by diclee** [comment]
Verify passed on sandbox.
