### ISSUE TITLE
KD: Make a Unix installation method for Klient (to install KD and Klient)

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9250]
A local installation of KD and Klient installs via the `kd install` command. This command does two main things. 1. downloads the klient binary, and 2. uses a library (https://github.com/koding/service) to interact with the Host OS to install Klient as a Service. This enabled Klient to automatically start on system start, and restart/etc with the hosts service commands (eg: `sudo service klient start`).

This library needs to either be replaced or improved, as it lacks functionality to support all OSs properly. Furthermore, there are some specific quirks in some OSs that need to be handled on a per-case basis. Eg, CentOS can come with a suoders setting that prevents Klient from starting (requiretty), so these individual issues will need to be supported/handled to make Klient work on all Unix OSs.

/cc: @rjeczalik

**Comment by rjeczalik** [comment]
Going to be taken care of via kd daemon install (#9886).
