### ISSUE TITLE
kd: add machine start/stop commands

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9252]
A requested feature is to add commands like `kd apple start` which would automatically start the `apple` machine just as if it was done from the Koding UI. Implementation would involve using the Kloud API, though permission work may have to be done to allow a user's klient to communicate with kloud directly.

/cc: @rjeczalik

**Comment by rjeczalik** [comment]
`kd machine start <label>`
`kd machine stop <label>`

Where `<label>` is jMachine.label (kd.io has no access to local-only fruit labels).
