### ISSUE TITLE
When user create new stack, It should be renamed regarding user's previous Stack Name

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9259]
Creating stack with same name makes confusion.
So Newly created Stack's name should be renamed regarding user's previous Stack names

**Comment by hakankaradis** [comment]
will be fixed with #9319 
/cc: @gokmen

**Comment by gokmen** [comment]
fixed.

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
