### ISSUE TITLE
'Remove Card' modal is different from the site-wide modal styling.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9270]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/19360660/41d4311a-9134-11e6-978c-e898c4060546.png)

**Comment by gokmen** [comment]
Can we also include credit card suffix, name or some reference to which card is going to be removed?

**Comment by usirin** [comment]
This modal became redundant, there will no be no way to remove a card, you can just change it.

**Comment by diclee** [comment]
Verify passed on sandbox.
