### ISSUE TITLE
Integrate webpack to docs/jekyll

### ISSUE THREAD

**Issue by usirin** [koding/koding#9315]
Right now our jekyll installation uses its own pipeline to build static assets. 

We need to make use of the current `webpack` infrastructure and make those modules which are available to the client, available to `jekyll` installation as well.

This part will be different from how the main app is built.

- Each page will have its own asset bundle which will be included in the specific `html` files inside `jekyll`. (e.g `payment.js` for payment related stuff, `team-create.js` for signup/login stuff, etc.)

| Script | Page | Url |
| ------ | ---- | --- |
| `home.js` | Home Page | `/` |
|`pricing.js` | Pricing | `/pricing` |
|`features.js` | Features | `/features` |
|`about.js` | About | `/about` |
|`login.js` | Login | `/teams/select` |
| `create-signup.js` | Create team by signing up | `/teams/create` |
| `create-login.js` | Create team by using an existing account | `/teams/create/existing` |

First iteration would be compiling them without thinking about creating a `common` chunk, depending on the result a second iteration may involve an optimization step where we bundle all the common code between scripts inside a `common.js` file.

/cc @sinan

**Comment by sinan** [comment]
After further thinking we decided to keep it simple, thus closing this.
