### ISSUE TITLE
Site is broken for people who have custom shortcuts

### ISSUE THREAD

**Issue by usirin** [koding/koding#9320]
App storage cache on client side app introduced in #9290 causes problems for people who has custom shortcut definitions prior to that PR.

This problem makes the whole app act weird as this causes problems in the `ShortcutsController` initialization phase, resulting in several errors, causing `singletons` after `ShortcutsController` to be not run at all.

We at least need to make it error prone so that other parts wouldn't stop running.

**Comment by usirin** [comment]
Fixed with #9333

**Comment by diclee** [comment]
Verify passed on latest.
