### ISSUE TITLE
ReadMe Preview and Credential Show Preview Modal's styling needs to be fixed

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9329]
![](https://monosnap.com/file/5IrUHlnOGvHTaxn0IWV9WxSgk5lDDX.png)
![](https://monosnap.com/file/cuttCZS3byHlzthnfhRLJuEcGcfbX5.png)

As shown in screenshots, these modal's styling is needs to fixed.
/cc: @ftasdelen, @diclee 
## Design changes

[New Modal Styling 04.pdf](https://github.com/koding/koding/files/545249/New.Modal.Styling.04.pdf)
## Acceptance Criteria

The pull request must
- [ ] satisfy all requirements
- [ ] provide screenshot for each modal
- [ ] satisfy [coffeescript style guideline](https://github.com/koding/styleguide-coffeescript)
- [ ] make sure all other windows are not affected with this changes.

If something is not clear, discuss it below.

**Comment by diclee** [comment]
Verify passed on latest.
