### ISSUE TITLE
Dashboard/Stacks: When default team stack has update, the tray icon styling needs to fixed 

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9358]
## Steps to Reproduce
- Create a team
- Build a team stack
- Update the team stack
- Dashboard/Stack section you will see something like screenshot.

![trayicon](https://cloud.githubusercontent.com/assets/5847301/19578482/b274a6b0-96d0-11e6-96ee-58007bdfdbc4.png)

/cc: @ftasdelen can you point where we need to put that little tray icon.

**Comment by diclee** [comment]
It's also misaligned for the private stacks: 
![image](https://cloud.githubusercontent.com/assets/8261892/19579187/12797812-96d4-11e6-9acd-71daf0e6d99b.png)

**Comment by ftasdelen** [comment]
If we have "Default" tag:
![image](https://cloud.githubusercontent.com/assets/306264/19581545/76c5b12e-96e2-11e6-97ae-178721a7f37a.png)

Without the tag:
![image](https://cloud.githubusercontent.com/assets/306264/19581527/6b88523a-96e2-11e6-8acb-76f70024dca6.png)

cc @hakankaradis @andrewjcasal @diclee

**Comment by usirin** [comment]
Fixed with #9384

**Comment by diclee** [comment]
Verify passed on latest.
