### ISSUE TITLE
kloud/userdata: hostname set by cloud-init is not resolvable

### ISSUE THREAD

**Issue by ppknap** [koding/koding#9381]
At machine bootstrapping Cloud-init injects machine's hostname to `/etc/hosts` file:

```
[sh, -c, 'echo \"127.0.0.1 ppknap\" >> /etc/hosts']
```

however google workers [replace](http://stackoverflow.com/questions/35762778/google-cloud-compute-engine-etc-hosts) them each time when machine is started:

``` sh
ppknap@ppknap:~$ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
169.254.169.254 metadata.google.internal metadata
```
## Expected Behavior

`/etc/hosts` should contain `127.0.0.1 hostname` entry.
## Current Behavior

`/etc/hosts` doesn't contain `127.0.0.1 hostname` entry.
## Possible Solution

Add [startup script](https://cloud.google.com/compute/docs/startupscript) that will add missing entry.
## Steps to Reproduce (for bugs)

Build GCE instance and check its `/etc/hosts`

**Comment by rjeczalik** [comment]
Question is why we needed this entry? This part of the cloud-init script comes from solo, if you ask me it's not needed now (/cc @gokmen) and we could just remove it from cloud-init.

**Comment by ppknap** [comment]
It only prevents errors like:
```
ppknap@ppknap:~$ sudo su
sudo: unable to resolve host ppknap
```
I didn't find it critical(even opposite - see labels). I created the issue just in case someone's complaining about it.

**Comment by rjeczalik** [comment]
Probably because we overwrite the Hostname in cloud-init to username, I think if we stop doing that, there'll be no such errors.

**Comment by rjeczalik** [comment]
I've just noticed [this](https://github.com/koding/koding/blob/master/go/src/koding/kites/kloud/userdata/userdata.go#L114).

🤕

**Comment by ppknap** [comment]
Oh, so it's disabled (I only examined cloud-init in tf.state file which is not very readable:) ). If we are not going to add hostname to `/etc/hosts`, feel free to close this issue.

**Comment by rjeczalik** [comment]
Let's take here care of:

```
sudo: unable to resolve host ppknap
```

Make cloud-init set hostname to the actual instance resource name, instead of username and add it to /etc/hosts.

**Comment by ppknap** [comment]
Fixed by new [provision script](https://github.com/koding/koding/commit/4a284283e242bb776665669573c15a2d7e1f6671#diff-7fc19b8d973da677cb3045b194252f81)
