### ISSUE TITLE
Running Vagrant Host in a VM

### ISSUE THREAD

**Issue by pavanagrawal123** [koding/koding#9410]
Hi! I was trying to set up a stack for my environment, and I did not have access to an AWS account. I tried to setup Vagrant, but I realized, you can't run that under a virtualized environment because of nested virtualization. Is there an option to run workspaces under docker like eclipse che does? I believe this would be a good option for people running koding under a private cloud w/ virtualization. 

Running on Ubuntu in a XEN environment...

Thanks!

**Comment by rjeczalik** [comment]
An option would be to use Docker provider for Vagrant.

There's an issue already on this with a rough outline [0] of the work needed to make that happen.

We welcome controbutions!

[0] https://github.com/koding/koding/issues/9230
