### ISSUE TITLE
High CPU load when KD tries to mount offline devices - performance issue.

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9481]
Context: https://koding.slack.com/archives/kd/p1477514766000073

Most likely closing https://github.com/koding/koding/issues/9306 would help fixing this issue, at least partially. From top of my head trying to fix `kd mount` / `kd remount` implementation to use some mount queue could help. If vm goes down or does not exist anymore the klient/remote tries hard to remount all cached mounts. Instead it should firstly invalidate not valid mounts and try at most N mounts at a time, which should also be configurable (so in the worst case it's possible to configure the amount of work `kd` and `klient` are doing, so user can change it - think niceness of a process).

**Comment by ppknap** [comment]
Done by: #10531 which also adds event queue and sync workers so the number of sync operations is always smaller than 2*Number of logical CPUs
