### ISSUE TITLE
Stack Template Preview modal should be resized for smaller screens.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9520]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20142161/4ca14c86-a69c-11e6-8719-8212f9889f15.png)

Modal title and close icon cannot be viewed when it's displayed on a smaller screen/window.

**Comment by hakankaradis** [comment]
It should be fixed with #9562

**Comment by diclee** [comment]
Verify passed on latest.
