### ISSUE TITLE
Boot2Docker deprecated

### ISSUE THREAD

**Issue by anonrig** [koding/koding#9525]
Boot2Docker command line interface is deprecated.

## Possible Solution
  WARNING: The 'boot2docker' command line interface (not to be confused with
  'boot2docker' the operating system) is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

## Steps to Reproduce (for bugs)
On the installation steps, running `./configure` and than `boot2docker start` gives this issue.

## Context
Support for deprecated command line interface is not available. Therefore, it's really hard to find a solution in the future to different issues encountered by the use case of boot2docker.

## Your Environment
Mac OSX
Koding go, node etc. versions are used in an exact way.

**Comment by cihangir** [comment]
Hi @anonrig , thanks for raising the issue, currently i have the "fix" in my localhost but, it is way too slow compared to b2docker. That is why we are still with Boot2Docker. @szkl reported the same problem as well.

my version is `docker-machine version 0.8.1, build 41b3b25`

**Comment by anonrig** [comment]
Thanks for the fast response @cihangir

Additionally, not relevant to this issue but, installing boot2docker requires virtualbox for the vms. the readme lacks from this issue. Without the virtualbox, boot2docker doesn't initialize the `boot2docker-vm` and therefore may mislead the developers who are trying to install koding from scratch.

**Comment by cihangir** [comment]
We officially support platform independent docker-compose https://github.com/koding/koding#getting-started-for-development If you find any problems with it lets update the docs. B2D is there for backward compatibility, no need to pollute readme with it. Thanks again.
