### ISSUE TITLE
When you open 'Virtual Machines' tab from a disabled user's stack, VM details are not expanded.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9534]
## Current Behavior
![gif](http://g.recordit.co/FCpwxt1BV1.gif)
http://recordit.co/FCpwxt1BV1

**Comment by hakankaradis** [comment]
@diclee We only expand the virtual machine section when you click to icon next to VM name in sidebar.
But I think we need to change this flow and when user click VMs from stack menu, it should go and expand the VM.

**Comment by diclee** [comment]
Verify passed on latest.
