### ISSUE TITLE
'Leave Shared VM' modal is appearing for disabled user's stack.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9535]
## Current Behavior
![gif](http://g.recordit.co/KzhNvtAKJg.gif)
http://recordit.co/KzhNvtAKJg

![gif](http://g.recordit.co/OEBPhI6hbt.gif)
http://recordit.co/OEBPhI6hbt

**Comment by hakankaradis** [comment]
@diclee can you please share the scenario, because you cannot share your disabled stack from dashboard.

You shared the vm and then disabled the user?

**Comment by diclee** [comment]
@hakankaradis no, I didn't share VM. I've just disabled the user and the disabled user's stack came with 'Leave Shared VM' modal on sidebar.

**Comment by diclee** [comment]
Verify passed on latest.
