### ISSUE TITLE
IDE becomes unstable when there are lots of tabs.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9537]
## Current Behavior
![gif](http://g.recordit.co/GTSgr4y61J.gif)
http://recordit.co/GTSgr4y61J
Tabs cannot be closed after having too many tabs and when file menu is not visible.

![gif](http://g.recordit.co/1rYj4XoSZh.gif)
http://recordit.co/1rYj4XoSZh

**Comment by hakankaradis** [comment]
@diclee I think it is totally style issue, I think the buttons which are `menu` and `x` buttons next to file name overlaps. I will take a look

**Comment by diclee** [comment]
Verify passed on latest.
