### ISSUE TITLE
File cannot be renamed from IDE header.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9539]
## Current Behavior
![gif](http://g.recordit.co/l9uQe9VWwX.gif)
http://recordit.co/l9uQe9VWwX

Editable mode on double click should be fixed or removed for files.

**Comment by hakankaradis** [comment]
@diclee I think the file that you are trying to rename has not been saved before.
So you cannot change its name. Can you please try again with saved file?

**Comment by diclee** [comment]
@hakankaradis I've tried with a saved file and it worked. But for the sake of user experience is it possible to disable renaming for an unsaved file?

**Comment by hakankaradis** [comment]
@diclee I removed the Rename menu item from dummy files. fyi

**Comment by diclee** [comment]
Verify passed on latest.
