### ISSUE TITLE
user-data is not working on Google Cloud stacks. 

### ISSUE THREAD

**Issue by diclee** [koding/koding#9540]
Example template:
```provider:
  google:
    credentials: '${var.google_credentials}'
    project: '${var.google_project}'
    region: '${var.google_region}'

resource:
  google_compute_instance:
    # this is the name of your VM
    google-instance:
      # and this is its identifier (required)
      name: google-instance
      # select your instance_type here: eg. n1-standard-1
      machine_type: f1-micro
      # base image for your instance
      disk:
        image: ubuntu-1404-lts
      # select your instance zone which must be in provided region: eg. us-central1-a
      zone: us-central1-a
      metadata:
        # on user_data section we will write bash and configure our VM
        user-data: |-
          # let's create a file on your root folder:
          echo "hello world!" >> /helloworld.txt
```

**Comment by diclee** [comment]
`ls /` output:
![image](https://cloud.githubusercontent.com/assets/8261892/20186942/b5705f98-a77a-11e6-97e7-553d1a4a9d71.png)

**Comment by rjeczalik** [comment]
@diclee Executing this line in bash:

```
echo "hello world!" >> /helloworld.txt```
```

Will cause shell to hang due to not-terminated ` expression. Please confirm it's not a typo in the stack template.

**Comment by diclee** [comment]
@rjeczalik this is the default stack template. That's why I've thought that it was a bug. Then, I'm assigning to @gokmen.

**Comment by gokmen** [comment]
@rjeczalik I've checked it out, it's correct in template @diclee just copy pasted incorrectly. There is an issue with `user_data` processing, template is correct.

**Comment by gokmen** [comment]
cc/ @ppknap

**Comment by gokmen** [comment]
here is the stacktemplate that it's used, fyi. https://github.com/koding/koding/blob/master/client/app/lib/providers/templates/google.coffee#L34-L67

**Comment by diclee** [comment]
Verify passed on sandbox.
