### ISSUE TITLE
Modal Overlay Design Update

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9570]
Main purpose of this issue, when boot VM modal is opened user should understand that sidebar is still clickable.
Update all overlay style for all modals.

Here is the design pdf file (sketch file will be shared with developer)
[Modal Overlay.pdf](https://github.com/koding/koding/files/590813/Sidebar.Highlight.05.pdf)

## Acceptance Criteria

The pull request have to include screenshots for all changes.

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
