### ISSUE TITLE
Virtual Machines cannot be displayed for Vagrant stacks with 'Cannot read property 'instanceTypes' of undefined' error on the console.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9576]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20306785/e819aef4-ab44-11e6-81ca-56c60ac184d5.png)

error log:
![image](https://cloud.githubusercontent.com/assets/8261892/20306802/fb0c391e-ab44-11e6-9976-2d8dbc2569fc.png)

**Comment by rjeczalik** [comment]
Probably the same bug applies to `Credentials` tab.

![pic](http://i.imgur.com/7Xx8rol.png)

**Comment by diclee** [comment]
Verify passed on latest.
