### ISSUE TITLE
'Leave Session' modal is appearing every time you click on a machine on sidebar.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9579]
## Current Behavior
![gif](http://g.recordit.co/enESEByr3J.gif)
http://recordit.co/enESEByr3J

**Comment by diclee** [comment]
@hakankaradis modal is not appearing when you click on another sidebar item anymore. But it's still appearing when you click on the collaboration machine. Is it the normal behavior?
![gif](http://g.recordit.co/MrPAYtTgbv.gif)
http://recordit.co/MrPAYtTgbv

**Comment by diclee** [comment]
@hakankaradis can you examine the above behavior when you have time? If it's ok, then we can close the issue.

**Comment by hakankaradis** [comment]
@diclee I think the modal should be opened only when we click the icon that is next to vm name.
I will send another fix for this bug. and sorry for my late answer

**Comment by diclee** [comment]
Verify passed on latest.
