### ISSUE TITLE
Old sessions are not listed in 'Sessions' list.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9580]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20315467/a14d3370-ab66-11e6-9eb2-c5e80bed6cd8.png)

**Comment by hakankaradis** [comment]
@diclee Couldn't reproduce.
Active tag style fixed.
![](https://monosnap.com/file/KFIhOtt8c5mi2ZuNzeyMORHwMyJ3Ce.png)

**Comment by hakankaradis** [comment]
I have tested on production and sandbox, It looks ok.
Closing this issue for now, please reopen If you can produce again. /cc: @diclee
