### ISSUE TITLE
There should be 'Email Address' label in the 'Find My Teams' textbox.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9581]
## Current Behavior
Find My Teams:
![image](https://cloud.githubusercontent.com/assets/8261892/20319030/547977f2-ab75-11e6-9e38-85fa87077c8c.png)

Forgot Password:
![image](https://cloud.githubusercontent.com/assets/8261892/20319053/63b00d44-ab75-11e6-894d-d54ffe0f3740.png)

**Comment by sinan** [comment]
👍

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
