### ISSUE TITLE
Incorrect font is loaded site-wide.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9584]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20319951/ca1aeb82-ab78-11e6-8b89-4b2c3d19dc40.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20319875/77e4d058-ab78-11e6-99c2-c0e538bad931.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20319797/2d14ebd0-ab78-11e6-887f-b4f18534589f.png)

If the font is correct and changed in purpose, then we need to fix the label and text alignments according to this font.
![image](https://cloud.githubusercontent.com/assets/8261892/20319767/122b7f8c-ab78-11e6-8344-a4d171c1e0fb.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20319784/1eed1960-ab78-11e6-9ff5-0ba899aacc40.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20319789/22bdfe38-ab78-11e6-8cc5-fe71ddc826d6.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20319810/356c9a4e-ab78-11e6-8f54-d79a7841c677.png)

**Comment by sinan** [comment]
@andrewjcasal can you please work on the broken fonts with @ftasdelen

**Comment by sinan** [comment]
Just use the mainfontfamily but do the necessary adjustments please.

**Comment by andrewjcasal** [comment]
https://github.com/koding/koding/pull/9588

**Comment by diclee** [comment]
Verify passed on sandbox & latest.
