### ISSUE TITLE
Watched files' headers are not displayed properly. 

### ISSUE THREAD

**Issue by diclee** [koding/koding#9603]
## Current Behavior
Filename and file icon are overlapping for watch only files.
![image](https://cloud.githubusercontent.com/assets/8261892/20389535/baa94e68-acd2-11e6-94ae-b689a8bb47fe.png)

**Comment by gokmen** [comment]
fixed with https://github.com/koding/koding/pull/9617

**Comment by diclee** [comment]
Verify passed on latest.
