### ISSUE TITLE
Managed VM is not working with 'Cannot read property 'isTestMachine' of undefined' error on the console.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9606]
## Current Behavior
error log:
![image](https://cloud.githubusercontent.com/assets/8261892/20392390/4fec5db4-ace0-11e6-9371-2a5ac7380010.png)
![image](https://cloud.githubusercontent.com/assets/8261892/20392401/5d3ca406-ace0-11e6-9441-fb292b072693.png)

**Comment by gokmen** [comment]
fixed with https://github.com/koding/koding/pull/9608

**Comment by rjeczalik** [comment]
Can it be closed?

**Comment by diclee** [comment]
Verify passed on latest.
