### ISSUE TITLE
Padding for the tags should be fixed.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9607]
## Current Behavior
After the font has changed, padding for the existing tags should be adjusted accordingly.
![image](https://cloud.githubusercontent.com/assets/8261892/20392933/a2ffe65e-ace2-11e6-801e-7d0922c113ac.png)
![image](https://cloud.githubusercontent.com/assets/8261892/20392975/ca00656c-ace2-11e6-8f1f-42bfdbf2616f.png)

**Comment by gokmen** [comment]
fixed with https://github.com/koding/koding/pull/9617

**Comment by diclee** [comment]
Verify passed on latest.
