### ISSUE TITLE
kd: add template subcommand

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9642]
Adds support for kd to create, list and publish templates.

TODO

- [x] kd: add frontend for `template init`
- [x] kd: add frontend for `template create`
- [ ] kd: add frontend for `template publish`
- [x] kd: add frontend for `template list`

Implements

`kd template init`
`kd template create`
`kd template publish`
`kd template list`

**Comment by rjeczalik** [comment]
I think we should not implement kloud backend for this one but use remote api directly with https://github.com/koding/koding/pull/9548. Wdyt? (/cc @gokmen)

If yes, during `kd auth login` (https://github.com/koding/koding/issues/9643) we should also get clientId to be able to talk to remote.api.

**Comment by gokmen** [comment]
@rjeczalik yes, we should start using the api for that since all the functionality already exists there. planning to make #9548 ready during the day and we can start iterating over it.
