### ISSUE TITLE
Can this be installed on premises?

### ISSUE THREAD

**Issue by pavanagrawal123** [koding/koding#9649]
## Expected Behavior
Koding to run on server onsite

## Current Behavior
Redirects don't work, POSTs fail...

## Steps to Reproduce (for bugs)
run docker commands
forwared port 8090 to koding instance
tried using hosts file to define redirected dns entries.... 

## Context
I'm just trying to run Koding on our internal infrastructure... Is this possible with the current setup?

## Your Environment
CentOS 7

**Comment by pavanagrawal123** [comment]
I have isoloated it down to the kite kontrol not connecting..... It says connection time out. I am using nip.io to do ip address dns.... What is the best way to go about doing DNS? ( I have set the host properly in the config, and it is sending to the correct server, but it is coming back as connection timed out). If the kite doesn't connect could this cause AWS keys to not verify? Every time I try to verify my AWS credentials, it says connection timed out.... Thanks for the help!

**Comment by szkl** [comment]
@pavanagrawal123 could you share your changes in configuration modules and any commands you've executed related to it?

**Comment by pavanagrawal123** [comment]
Hi!

Here is what I using for the Docker YML
`
version: '2'

services:
  koding:
    image: koding/koding:20160921
    command: --version 20160921 --service-ports backend /opt/koding/scripts/bootstrap-container build --host=10.1.10.XXX.nip.io
    env_file: .env-docker-compose
    ports:
      - "8090:8090"
    links:
      - mongo
      - postgres
      - redis
      - rabbitmq

  mongo:
    image: koding/mongo:20160906

  rabbitmq:
    image: rabbitmq:3-management

  postgres:
    image: koding/postgres:20160824

  redis:
    image: redis`

Also, I can't find any documentation over this..... Can you link me to any talking about on-premise installation? Please note, I am trying to connect over the local network (using the nip.io), do remote ports need to be forwarded? If so, which ones?

**Comment by pavanagrawal123** [comment]
Hi @szkl 

is there any update?

**Comment by szkl** [comment]
Hello @pavanagrawal123. Sorry for the very late response.

I can only say `--service-ports` is not right at this point. That option is recognized by `docker-compose` command. It doesn't have any effect with `bootstrap-container` script. Otherwise, it looks good to me.

Port 8090 is the default for main web server. It should be accessible via `10.1.10.XXX.nip.io:8090`. We have to confirm that first.

I will try out your use case to get a better understanding. We don't have a documentation for local network setup yet.

**Comment by pavanagrawal123** [comment]
Hi!

Thanks for the response. I was able to run it by editing the config when i used these steps:
`git clone https://github.com/koding/koding.git
cd koding
docker-compose -f docker-compose-init.yml run init
docker-compose up`

I did this a while back so I don't remember what was the result of editing the config, but I do remember the web server worked fine. The issue was that the the KITE would not connect to it. It was pointing to the correct IP, but it would just give a connection timed out. I tried from both a Digital Ocean Instance and a server in my local network. I will try again later today and let you know some more details.

**Comment by szkl** [comment]
It times out because IP address belongs to private subnet range. You have to make koding publicly available currently. We're going to investigate how to setup properly in a private network.

**Comment by szkl** [comment]
@pavanagrawal123 do you have any updates for me?

**Comment by pavanagrawal123** [comment]
Hi!

Sorry for not responding. I should have more info this weekend. Thanks.



On Fri, Dec 23, 2016 at 12:04 PM -0600, "Sönmez Kartal" <notifications@github.com<mailto:notifications@github.com>> wrote:


@pavanagrawal123<https://github.com/pavanagrawal123> do you have any updates for me?
