### ISSUE TITLE
Dashboard: Change role menu in Teammate section is not appeared.

### ISSUE THREAD

**Issue by hakankaradis** [koding/koding#9655]
The usage of `React-Portal` library changed.
`react-portal` version 3.0 usage seems different than the usage that we have currently.
/cc: @usirin

**Comment by gokmen** [comment]
it's probably related the issue fixed with https://github.com/koding/koding/pull/9631 ref: https://github.com/tajo/react-portal/commit/e02033099af03a53262bf43110b7adf84f75d273

**Comment by diclee** [comment]
Verify passed on latest.
