### ISSUE TITLE
kd: add team subcommand

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9689]
Adds support for kd to list and login to teams. Adds support for generic kd-io team.

TODO

- [x] kloud: add backend for `team list`
- [x] kd: add frontend for `team list`
- [x] kd: add frontend for `team use`

Implements

`kd auth login --team`
`kd team list`
`kd team use`

**Comment by usirin** [comment]
@ppknap What is the status update with this issue? Does the closed PR (#9852) implement all the requirements?

**Comment by rjeczalik** [comment]
@usirin Yes, #9852 added `team list`, I've added `auth login --team` in a separate PR. Can be closed.

Sorry, there's a mess currently in the backlog, we're going to clean it up.

**Comment by usirin** [comment]
> Sorry, there's a mess currently in the backlog, we're going to clean it up.

👍 That would be amazing.
