### ISSUE TITLE
Filetree is not working if expected home directory doesn't exist.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9756]
## Expected Behavior
It should at least fallback to '/' directory

## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20622269/b1ea3542-b30a-11e6-9211-59b405bbdd29.png)

It works properly when top folder is changed:
![image](https://cloud.githubusercontent.com/assets/8261892/20622312/f297ae26-b30a-11e6-8315-52212f8e464c.png)

cc @rjeczalik This is the situation for Marathon provider currently.

**Comment by rjeczalik** [comment]
> This is the situation for Marathon provider currently.

The home directory is assumed to be `/home/user`, however in a container klient always runs as root. Either use `/` or call klient kite with methods `os.currentUsername` + `os.home` to find home for a user that klient is started with.

**Comment by gokmen** [comment]
yup, IDE was designed like that and my old request is coming along; what about providing this info from klient for the current user? like `klient.info` can return;

```json
{
  username: 'foobar'
  home: '/home/foobar'
  groups: ['users', 'sudo', ...]
}
```

wdyt?

**Comment by rjeczalik** [comment]
@gokmen I've extended klient.info according to your suggestion and deployed klient to development channel.

**Comment by gokmen** [comment]
@rjeczalik I'll update IDE to use that information 👍

**Comment by diclee** [comment]
Verify passed on sandbox.

**Comment by diclee** [comment]
Verify failed on latest probably because of klient updates haven't deployed to production channel yet.

**Comment by diclee** [comment]
Verify passed on latest.
