### ISSUE TITLE
Apply for Koding Credit form

### ISSUE THREAD

**Issue by sinan** [koding/koding#9801]
Create a landing page at www.koding.com/apply-for-credit and re-create [this](https://docs.google.com/forms/d/e/1FAIpQLSerI66cyUfGdqNRmx-oJAOP2QLJEpWGAMFTxzssy_0bsDPA-g/viewform?c=0&w=1) form by using a wufoo form as backend. Like it's done in [here](www.koding.com/demo).

## Expected Behavior
- once the form is submitted it should create an entry in wufoo

**Comment by andrewjcasal** [comment]
Fixed with https://github.com/koding/koding/pull/10080
