### ISSUE TITLE
Auto-filled credit card is not working on latest and a new card cannot be entered.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9833]
## Current Behavior
Therefore team cannot be created on latest.
![gif](http://g.recordit.co/G7YaSOCB3E.gif)
http://recordit.co/G7YaSOCB3E

**Comment by szkl** [comment]
Test credit card doesn't work on production environments.

**Comment by diclee** [comment]
Therefore that step needs to be removed from latest environment or a working credit card should be entered for testing purposes. Otherwise latest becomes useless.

**Comment by diclee** [comment]
@usirin credit card input fields are not editable and 'use different card' link also doesn't work. As a result testing cannot be done on latest environment.

**Comment by diclee** [comment]
Verify passed on latest.
