### ISSUE TITLE
Minor change on default stack template (for stack script docs reference)

### ISSUE THREAD

**Issue by diclee** [koding/koding#9835]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20762722/05301ce8-b730-11e6-959c-071e10189e09.png)

**Comment by gokmen** [comment]
@hakankaradis can u update all stack template examples?

**Comment by hakankaradis** [comment]
![](https://monosnap.com/file/z3jozxfUNwGso49y9RpuWjISEjqLP6.png)
@diclee we hide it. I will update the comment in the default stack template

**Comment by diclee** [comment]
Verify passed on sandbox.
