### ISSUE TITLE
Console is full of 'internal server error' on sandbox.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9836]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20763162/9858cb86-b731-11e6-9b97-2f4dfc14d9d9.png)

![image](https://cloud.githubusercontent.com/assets/8261892/20763190/adca910c-b731-11e6-9989-f5b9e7660f2d.png)

**Comment by rjeczalik** [comment]
Related: https://github.com/koding/koding/pull/9845 https://github.com/koding/koding/pull/9848

**Comment by diclee** [comment]
Verify passed on sandbox.
