### ISSUE TITLE
Team cannot be created on sandbox with a JSON error in the console.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9842]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20787248/8e46e420-b7b3-11e6-9a5a-4ab42d8a65d3.png)

It gets stuck on credit card verification step.

**Comment by cihangir** [comment]
fixed by https://github.com/koding/koding/pull/9845

**Comment by diclee** [comment]
Verify passed on sandbox.
