### ISSUE TITLE
kd: rework for "daemon install" command

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9886]
Make it possible to install dependencies for KD Daemon from kd.

TODO

- [x] klient: rework installation to be able to `brew install kd`
- [x] klient/daemon: install
- [x] klient/daemon: uninstall
- [x] klient/daemon: start
- [x] klient/daemon: stop
- [ ] klient/daemon: improve UI
- [ ] klient/daemon: rollback

**Comment by ppknap** [comment]
@rjeczalik can we close this?
