### ISSUE TITLE
Fix Rainforest QA test specifications for $5 / step

### ISSUE THREAD

**Issue by szkl** [koding/koding#9891]
0. Fork https://github.com/koding/koding repository
1. Ask for a Rainforest QA account
2. Pick a failed test in results [page](https://app.rainforestqa.com/runs)
3. Open the related test file in [this](https://github.com/koding/koding/tree/master/tests/spec/rainforest) directory. Test file has the same name as the title of the test 
3a. Click to "Go to test" link on top right corner
4. Click to "Preview Test" button
5. Select "Sandbox (default)" environment
6. Select "Google Chrome - OS X" browser
7. Click to "Open Preview" button
8. Click to "I Understand" button at the bottom
9. Follow the steps
10. Make the changes required to fix test specification when you see a mistake or test is not written properly. Make sure test step is written in simple and proper English
11. Continue testing remaining steps in the same test
12. Send a pull request to master branch in koding/koding repository when you're sure you have fixed all the errors
13. Wait until Rainforest test run is completed. Check the result of the test file that you have fixed
14. If all tests have passed then contact your supervisor. You'll receive $5 per step you have fixed. A single test file contains approximately 30 steps

Supervisors for this issue are @szkl @diclee @hakankaradis. Please contact a supervisor if you have any questions.

Comment on this issue regarding which test you are going to work on and your deadline estimation. This is necessary to avoid conflicts with multiple people working on the same test specification.

If you'd like to join this effort ask for a Rainforest account from one of the supervisors.

**Comment by kwagdy** [comment]
finished: `sharedVMs_uploadFileByDragDrop.rfml`

**Comment by kwagdy** [comment]
finished: `collaboration_reject_accept_invitation.rfml`

**Comment by kwagdy** [comment]
started on: `sharedVMs_reject_inviteAgain_accept_checkTerminalActions`...

**Comment by hectork01** [comment]
Working oin `skipGuide_custom_userData_variables_readme_templatePreviewClick`
Fixing instructions when looking for the aws key.

**Comment by hectork01** [comment]
Working on: `createTeam_usingAlreadyRegisteredEmail_afterClickingFreshAccount`
Editing step 5, for some users is showing different message that 'Please enter your _sandbox.koding.com_ username & password.'

**Comment by hectork01** [comment]
Working on `show_edit_remove_credentials` adding instructions to clarify the steps to follow
