### ISSUE TITLE
User needs to reload the page after adding a credit card to an existing team.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9924]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20965342/dd94e1ca-bc7d-11e6-948b-f07539da8c5d.png)

**Comment by diclee** [comment]
might be related with #9348.

**Comment by usirin** [comment]
This will be fixed by:
- Reloading at the same page after user clicks to `Close` button.
- Redirecting with reload to the member invite form after user clicks to `Invite Members` button.

![Alt text](https://monosnap.com/file/KwtVdDuKENl8GrnWthO8kpCH7llmzZ.png)

**Comment by diclee** [comment]
Verify passed on sandbox.
