### ISSUE TITLE
klient/kd: extend kite auth with team information

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9926]
Currently no klient has information about which team it's being run in.

In order to integrate accurately with payment system kd and klient needs to know their team names.

This information can be store either in:

- bolt (not tamper-proof)
- kite.key's claims (tamper-proof)

TODO is to to:

- [ ] for new kd installations read jSessions.groupName upon registration and attach to kite.key
- [ ] for new klient deployments make kloud attach team name to kite.key
- [ ] for existing klients / kds we update existing kite.key with username; heuristics for matching kites and teams:
   - [ ] for klient (on aws etc.) we match kite's RegisterURL.Host with jMachine.ipAddress and lookup team name by jMachine.groups[0].Id
   - [ ] for kd on user's laptop we basically do the same like above with fallback to picking the most recently active team name basing on jSessions.lastAccess for the authorized kite's username

/cc @gokmen @cihangir @ppknap

**Comment by gokmen** [comment]
do we need it to store? as you pointed can't we use the data that we've in session already?

**Comment by rjeczalik** [comment]
@gokmen kd and klient has no session; moreover existing klients can't auth-login, since there's also no team infor.

Alternative solution that I just thought of is to force existing users with new kd version that users should `kd auth login --team their_team`.

The problem here is that team information is required in order to make kd visible in presence, but kd currently does not know anything about teams. There's an ongoing effort to rewrite kd to use kloud instead of kontrol (so it will have team info), but payment should be integrated before we manage to finalize that effort.

**Comment by ppknap** [comment]
@gokmen I also need team information for kd mounts and for blocking on unpaid subscription(which is per team). @rjeczalik we can use `kd auth login --team xyz` but it's better to have consistent team info logic on both managed and remote klients.
