### ISSUE TITLE
payment: credits are not reflected properly on payment dashboard

### ISSUE THREAD

**Issue by cihangir** [koding/koding#9944]
## Expected Behavior
Free credit should include account balance

## Current Behavior
it does not show

## Possible Solution
add account balance in negative form to credit.

## Steps to Reproduce (for bugs)
1. add free credit to an account from cebeci
2.see if it is reflected on billing page

## Context
![image](https://cloud.githubusercontent.com/assets/879660/21007866/91e049d4-bd47-11e6-8531-eede165dc742.png)

**Comment by diclee** [comment]
Verify passed on latest.
