### ISSUE TITLE
Deleted shared stack template is removed from member's list after reloading the page.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9946]
## Current Behavior
![gif](http://g.recordit.co/JUETLZ0t6W.gif)
http://recordit.co/JUETLZ0t6W

**Comment by hakankaradis** [comment]
@dicle couldn't reproduce 
here is the screencast
http://recordit.co/ZUb3gUbrgw

**Comment by diclee** [comment]
This issue is not reproducible anymore. Closing.
