### ISSUE TITLE
Minor UI issues on the 'Do you want to save your changes' modal.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9975]
## Current Behavior
Modal appearing when you try to close an IDE tab without saving changes:
![image](https://cloud.githubusercontent.com/assets/8261892/21046329/dd850c60-be0c-11e6-9809-cbd4b0bf7a93.png)

- title vertically misaligned
- `x` icon's clickable area is too small

**Comment by andrewjcasal** [comment]
https://github.com/koding/koding/pull/10252

**Comment by andrewjcasal** [comment]
Pull request https://github.com/koding/koding/pull/10252 found here.

**Comment by diclee** [comment]
Verify passed on sandbox.
